/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.integrations.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class UpdateIntegrationsResponseDataType {
    public static final UpdateIntegrationsResponseDataType OKTA =
            new UpdateIntegrationsResponseDataType(Value.OKTA, "OKTA");

    public static final UpdateIntegrationsResponseDataType SLACK =
            new UpdateIntegrationsResponseDataType(Value.SLACK, "SLACK");

    public static final UpdateIntegrationsResponseDataType HUBSPOT =
            new UpdateIntegrationsResponseDataType(Value.HUBSPOT, "HUBSPOT");

    public static final UpdateIntegrationsResponseDataType SALESFORCE =
            new UpdateIntegrationsResponseDataType(Value.SALESFORCE, "SALESFORCE");

    public static final UpdateIntegrationsResponseDataType DISCORD =
            new UpdateIntegrationsResponseDataType(Value.DISCORD, "DISCORD");

    public static final UpdateIntegrationsResponseDataType AUTH0 =
            new UpdateIntegrationsResponseDataType(Value.AUTH0, "AUTH0");

    private final Value value;

    private final String string;

    UpdateIntegrationsResponseDataType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof UpdateIntegrationsResponseDataType
                        && this.string.equals(((UpdateIntegrationsResponseDataType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OKTA:
                return visitor.visitOkta();
            case SLACK:
                return visitor.visitSlack();
            case HUBSPOT:
                return visitor.visitHubspot();
            case SALESFORCE:
                return visitor.visitSalesforce();
            case DISCORD:
                return visitor.visitDiscord();
            case AUTH0:
                return visitor.visitAuth0();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UpdateIntegrationsResponseDataType valueOf(String value) {
        switch (value) {
            case "OKTA":
                return OKTA;
            case "SLACK":
                return SLACK;
            case "HUBSPOT":
                return HUBSPOT;
            case "SALESFORCE":
                return SALESFORCE;
            case "DISCORD":
                return DISCORD;
            case "AUTH0":
                return AUTH0;
            default:
                return new UpdateIntegrationsResponseDataType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SLACK,

        DISCORD,

        SALESFORCE,

        HUBSPOT,

        OKTA,

        AUTH0,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitSlack();

        T visitDiscord();

        T visitSalesforce();

        T visitHubspot();

        T visitOkta();

        T visitAuth0();

        T visitUnknown(String unknownType);
    }
}
