/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.provisioning.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.resources.provisioning.types.InviteTeamProvisioningRequestMembersItem;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InviteTeamProvisioningRequest.Builder.class)
public final class InviteTeamProvisioningRequest {
    private final String provisioningKey;

    private final String handle;

    private final List<InviteTeamProvisioningRequestMembersItem> members;

    private final Map<String, Object> additionalProperties;

    private InviteTeamProvisioningRequest(
            String provisioningKey,
            String handle,
            List<InviteTeamProvisioningRequestMembersItem> members,
            Map<String, Object> additionalProperties) {
        this.provisioningKey = provisioningKey;
        this.handle = handle;
        this.members = members;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return User provisioning key for platform-level instance management
     */
    @JsonIgnore
    public String getProvisioningKey() {
        return provisioningKey;
    }

    @JsonProperty("handle")
    public String getHandle() {
        return handle;
    }

    @JsonProperty("members")
    public List<InviteTeamProvisioningRequestMembersItem> getMembers() {
        return members;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InviteTeamProvisioningRequest && equalTo((InviteTeamProvisioningRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InviteTeamProvisioningRequest other) {
        return provisioningKey.equals(other.provisioningKey)
                && handle.equals(other.handle)
                && members.equals(other.members);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provisioningKey, this.handle, this.members);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProvisioningKeyStage builder() {
        return new Builder();
    }

    public interface ProvisioningKeyStage {
        /**
         * <p>User provisioning key for platform-level instance management</p>
         */
        HandleStage provisioningKey(@NotNull String provisioningKey);

        Builder from(InviteTeamProvisioningRequest other);
    }

    public interface HandleStage {
        _FinalStage handle(@NotNull String handle);
    }

    public interface _FinalStage {
        InviteTeamProvisioningRequest build();

        _FinalStage members(List<InviteTeamProvisioningRequestMembersItem> members);

        _FinalStage addMembers(InviteTeamProvisioningRequestMembersItem members);

        _FinalStage addAllMembers(List<InviteTeamProvisioningRequestMembersItem> members);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProvisioningKeyStage, HandleStage, _FinalStage {
        private String provisioningKey;

        private String handle;

        private List<InviteTeamProvisioningRequestMembersItem> members = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InviteTeamProvisioningRequest other) {
            provisioningKey(other.getProvisioningKey());
            handle(other.getHandle());
            members(other.getMembers());
            return this;
        }

        /**
         * <p>User provisioning key for platform-level instance management</p>
         * <p>User provisioning key for platform-level instance management</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public HandleStage provisioningKey(@NotNull String provisioningKey) {
            this.provisioningKey = Objects.requireNonNull(provisioningKey, "provisioningKey must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("handle")
        public _FinalStage handle(@NotNull String handle) {
            this.handle = Objects.requireNonNull(handle, "handle must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllMembers(List<InviteTeamProvisioningRequestMembersItem> members) {
            if (members != null) {
                this.members.addAll(members);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addMembers(InviteTeamProvisioningRequestMembersItem members) {
            this.members.add(members);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "members", nulls = Nulls.SKIP)
        public _FinalStage members(List<InviteTeamProvisioningRequestMembersItem> members) {
            this.members.clear();
            if (members != null) {
                this.members.addAll(members);
            }
            return this;
        }

        @java.lang.Override
        public InviteTeamProvisioningRequest build() {
            return new InviteTeamProvisioningRequest(provisioningKey, handle, members, additionalProperties);
        }
    }
}
