/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.provisioning.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RemoveTeamMemberProvisioningRequest.Builder.class)
public final class RemoveTeamMemberProvisioningRequest {
    private final String provisioningKey;

    private final String handle;

    private final String email;

    private final Map<String, Object> additionalProperties;

    private RemoveTeamMemberProvisioningRequest(
            String provisioningKey, String handle, String email, Map<String, Object> additionalProperties) {
        this.provisioningKey = provisioningKey;
        this.handle = handle;
        this.email = email;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return User provisioning key for platform-level instance management
     */
    @JsonIgnore
    public String getProvisioningKey() {
        return provisioningKey;
    }

    @JsonProperty("handle")
    public String getHandle() {
        return handle;
    }

    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RemoveTeamMemberProvisioningRequest
                && equalTo((RemoveTeamMemberProvisioningRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RemoveTeamMemberProvisioningRequest other) {
        return provisioningKey.equals(other.provisioningKey)
                && handle.equals(other.handle)
                && email.equals(other.email);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provisioningKey, this.handle, this.email);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProvisioningKeyStage builder() {
        return new Builder();
    }

    public interface ProvisioningKeyStage {
        /**
         * <p>User provisioning key for platform-level instance management</p>
         */
        HandleStage provisioningKey(@NotNull String provisioningKey);

        Builder from(RemoveTeamMemberProvisioningRequest other);
    }

    public interface HandleStage {
        EmailStage handle(@NotNull String handle);
    }

    public interface EmailStage {
        _FinalStage email(@NotNull String email);
    }

    public interface _FinalStage {
        RemoveTeamMemberProvisioningRequest build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProvisioningKeyStage, HandleStage, EmailStage, _FinalStage {
        private String provisioningKey;

        private String handle;

        private String email;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RemoveTeamMemberProvisioningRequest other) {
            provisioningKey(other.getProvisioningKey());
            handle(other.getHandle());
            email(other.getEmail());
            return this;
        }

        /**
         * <p>User provisioning key for platform-level instance management</p>
         * <p>User provisioning key for platform-level instance management</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public HandleStage provisioningKey(@NotNull String provisioningKey) {
            this.provisioningKey = Objects.requireNonNull(provisioningKey, "provisioningKey must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("handle")
        public EmailStage handle(@NotNull String handle) {
            this.handle = Objects.requireNonNull(handle, "handle must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("email")
        public _FinalStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        @java.lang.Override
        public RemoveTeamMemberProvisioningRequest build() {
            return new RemoveTeamMemberProvisioningRequest(provisioningKey, handle, email, additionalProperties);
        }
    }
}
