/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.integrations;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.ForumClientApiException;
import com.foru.ms.api.core.ForumClientException;
import com.foru.ms.api.core.ForumClientHttpResponse;
import com.foru.ms.api.core.MediaTypes;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.core.QueryStringMapper;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.errors.BadRequestError;
import com.foru.ms.api.errors.InternalServerError;
import com.foru.ms.api.errors.NotFoundError;
import com.foru.ms.api.errors.PaymentRequiredError;
import com.foru.ms.api.errors.TooManyRequestsError;
import com.foru.ms.api.errors.UnauthorizedError;
import com.foru.ms.api.resources.integrations.requests.CreateIntegrationsRequest;
import com.foru.ms.api.resources.integrations.requests.DeleteIntegrationsRequest;
import com.foru.ms.api.resources.integrations.requests.ListIntegrationsRequest;
import com.foru.ms.api.resources.integrations.requests.RetrieveIntegrationsRequest;
import com.foru.ms.api.resources.integrations.requests.UpdateIntegrationsRequest;
import com.foru.ms.api.resources.integrations.types.UpdateIntegrationsResponse;
import com.foru.ms.api.types.ErrorResponse;
import com.foru.ms.api.types.IntegrationListResponse;
import com.foru.ms.api.types.IntegrationResponse;
import com.foru.ms.api.types.SuccessResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawIntegrationsClient {
    protected final ClientOptions clientOptions;

    public RawIntegrationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve a paginated list of integrations. Use cursor for pagination.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationListResponse> list() {
        return list(ListIntegrationsRequest.builder().build());
    }

    /**
     * Retrieve a paginated list of integrations. Use cursor for pagination.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationListResponse> list(RequestOptions requestOptions) {
        return list(ListIntegrationsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve a paginated list of integrations. Use cursor for pagination.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationListResponse> list(ListIntegrationsRequest request) {
        return list(request, null);
    }

    /**
     * Retrieve a paginated list of integrations. Use cursor for pagination.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationListResponse> list(
            ListIntegrationsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("integrations");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "cursor", request.getCursor().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IntegrationListResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Create an new integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> create(CreateIntegrationsRequest request) {
        return create(request, null);
    }

    /**
     * Create an new integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> create(
            CreateIntegrationsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("integrations")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IntegrationResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieve an integration by ID or slug (if supported).
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> retrieve(String id) {
        return retrieve(id, RetrieveIntegrationsRequest.builder().build());
    }

    /**
     * Retrieve an integration by ID or slug (if supported).
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> retrieve(String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveIntegrationsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve an integration by ID or slug (if supported).
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> retrieve(String id, RetrieveIntegrationsRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Retrieve an integration by ID or slug (if supported).
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<IntegrationResponse> retrieve(
            String id, RetrieveIntegrationsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("integrations")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IntegrationResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Permanently delete an integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id) {
        return delete(id, DeleteIntegrationsRequest.builder().build());
    }

    /**
     * Permanently delete an integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id, RequestOptions requestOptions) {
        return delete(id, DeleteIntegrationsRequest.builder().build(), requestOptions);
    }

    /**
     * Permanently delete an integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id, DeleteIntegrationsRequest request) {
        return delete(id, request, null);
    }

    /**
     * Permanently delete an integration.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(
            String id, DeleteIntegrationsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("integrations")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update an existing integration. Only provided fields will be modified.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<UpdateIntegrationsResponse> update(String id) {
        return update(id, UpdateIntegrationsRequest.builder().build());
    }

    /**
     * Update an existing integration. Only provided fields will be modified.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<UpdateIntegrationsResponse> update(String id, RequestOptions requestOptions) {
        return update(id, UpdateIntegrationsRequest.builder().build(), requestOptions);
    }

    /**
     * Update an existing integration. Only provided fields will be modified.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<UpdateIntegrationsResponse> update(String id, UpdateIntegrationsRequest request) {
        return update(id, request, null);
    }

    /**
     * Update an existing integration. Only provided fields will be modified.
     * <p><strong>Requires feature: integrations</strong></p>
     */
    public ForumClientHttpResponse<UpdateIntegrationsResponse> update(
            String id, UpdateIntegrationsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("integrations")
                .addPathSegment(id)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateIntegrationsResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }
}
