/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.posts.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.resources.posts.types.ListReactionsPostsRequestType;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListReactionsPostsRequest.Builder.class)
public final class ListReactionsPostsRequest {
    private final Optional<Integer> limit;

    private final Optional<String> cursor;

    private final Optional<ListReactionsPostsRequestType> type;

    private final Map<String, Object> additionalProperties;

    private ListReactionsPostsRequest(
            Optional<Integer> limit,
            Optional<String> cursor,
            Optional<ListReactionsPostsRequestType> type,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.cursor = cursor;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Items per page (max 75)
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Cursor for pagination
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    /**
     * @return Filter by reaction type
     */
    @JsonProperty("type")
    public Optional<ListReactionsPostsRequestType> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListReactionsPostsRequest && equalTo((ListReactionsPostsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListReactionsPostsRequest other) {
        return limit.equals(other.limit) && cursor.equals(other.cursor) && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.limit, this.cursor, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Optional<ListReactionsPostsRequestType> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListReactionsPostsRequest other) {
            limit(other.getLimit());
            cursor(other.getCursor());
            type(other.getType());
            return this;
        }

        /**
         * <p>Items per page (max 75)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Cursor for pagination</p>
         */
        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * <p>Filter by reaction type</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<ListReactionsPostsRequestType> type) {
            this.type = type;
            return this;
        }

        public Builder type(ListReactionsPostsRequestType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public ListReactionsPostsRequest build() {
            return new ListReactionsPostsRequest(limit, cursor, type, additionalProperties);
        }
    }
}
