/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.users;

import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.resources.users.requests.DeleteUsersIdFollowersSubIdRequest;
import com.foru.ms.api.resources.users.requests.DeleteUsersIdFollowingSubIdRequest;
import com.foru.ms.api.resources.users.requests.DeleteUsersIdRequest;
import com.foru.ms.api.resources.users.requests.GetUsersIdFollowersRequest;
import com.foru.ms.api.resources.users.requests.GetUsersIdFollowersSubIdRequest;
import com.foru.ms.api.resources.users.requests.GetUsersIdFollowingRequest;
import com.foru.ms.api.resources.users.requests.GetUsersIdFollowingSubIdRequest;
import com.foru.ms.api.resources.users.requests.GetUsersIdRequest;
import com.foru.ms.api.resources.users.requests.GetUsersRequest;
import com.foru.ms.api.resources.users.requests.PatchUsersIdRequest;
import com.foru.ms.api.resources.users.types.DeleteUsersIdFollowersSubIdResponse;
import com.foru.ms.api.resources.users.types.DeleteUsersIdFollowingSubIdResponse;
import com.foru.ms.api.resources.users.types.DeleteUsersIdResponse;
import com.foru.ms.api.resources.users.types.GetUsersIdFollowersResponse;
import com.foru.ms.api.resources.users.types.GetUsersIdFollowersSubIdResponse;
import com.foru.ms.api.resources.users.types.GetUsersIdFollowingResponse;
import com.foru.ms.api.resources.users.types.GetUsersIdFollowingSubIdResponse;
import com.foru.ms.api.resources.users.types.GetUsersIdResponse;
import com.foru.ms.api.resources.users.types.GetUsersResponse;
import com.foru.ms.api.resources.users.types.PatchUsersIdResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncUsersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawUsersClient rawClient;

    public AsyncUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawUsersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawUsersClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<GetUsersResponse> listAllUsers() {
        return this.rawClient.listAllUsers().thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersResponse> listAllUsers(RequestOptions requestOptions) {
        return this.rawClient.listAllUsers(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersResponse> listAllUsers(GetUsersRequest request) {
        return this.rawClient.listAllUsers(request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersResponse> listAllUsers(GetUsersRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAllUsers(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdResponse> getAUser(String id) {
        return this.rawClient.getAUser(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdResponse> getAUser(String id, RequestOptions requestOptions) {
        return this.rawClient.getAUser(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdResponse> getAUser(String id, GetUsersIdRequest request) {
        return this.rawClient.getAUser(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdResponse> getAUser(
            String id, GetUsersIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAUser(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdResponse> deleteAUser(String id) {
        return this.rawClient.deleteAUser(id).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdResponse> deleteAUser(String id, RequestOptions requestOptions) {
        return this.rawClient.deleteAUser(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdResponse> deleteAUser(String id, DeleteUsersIdRequest request) {
        return this.rawClient.deleteAUser(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdResponse> deleteAUser(
            String id, DeleteUsersIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteAUser(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchUsersIdResponse> updateAUser(String id) {
        return this.rawClient.updateAUser(id).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchUsersIdResponse> updateAUser(String id, RequestOptions requestOptions) {
        return this.rawClient.updateAUser(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchUsersIdResponse> updateAUser(String id, PatchUsersIdRequest request) {
        return this.rawClient.updateAUser(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchUsersIdResponse> updateAUser(
            String id, PatchUsersIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateAUser(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersResponse> listUserFollowers(String id) {
        return this.rawClient.listUserFollowers(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersResponse> listUserFollowers(String id, RequestOptions requestOptions) {
        return this.rawClient.listUserFollowers(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersResponse> listUserFollowers(
            String id, GetUsersIdFollowersRequest request) {
        return this.rawClient.listUserFollowers(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersResponse> listUserFollowers(
            String id, GetUsersIdFollowersRequest request, RequestOptions requestOptions) {
        return this.rawClient.listUserFollowers(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersSubIdResponse> getAFollowerFromUser(String id, String subId) {
        return this.rawClient.getAFollowerFromUser(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersSubIdResponse> getAFollowerFromUser(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.getAFollowerFromUser(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersSubIdResponse> getAFollowerFromUser(
            String id, String subId, GetUsersIdFollowersSubIdRequest request) {
        return this.rawClient.getAFollowerFromUser(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowersSubIdResponse> getAFollowerFromUser(
            String id, String subId, GetUsersIdFollowersSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAFollowerFromUser(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowersSubIdResponse> deleteAFollowerFromUser(String id, String subId) {
        return this.rawClient.deleteAFollowerFromUser(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowersSubIdResponse> deleteAFollowerFromUser(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.deleteAFollowerFromUser(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowersSubIdResponse> deleteAFollowerFromUser(
            String id, String subId, DeleteUsersIdFollowersSubIdRequest request) {
        return this.rawClient.deleteAFollowerFromUser(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowersSubIdResponse> deleteAFollowerFromUser(
            String id, String subId, DeleteUsersIdFollowersSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .deleteAFollowerFromUser(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingResponse> listUserFollowing(String id) {
        return this.rawClient.listUserFollowing(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingResponse> listUserFollowing(String id, RequestOptions requestOptions) {
        return this.rawClient.listUserFollowing(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingResponse> listUserFollowing(
            String id, GetUsersIdFollowingRequest request) {
        return this.rawClient.listUserFollowing(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingResponse> listUserFollowing(
            String id, GetUsersIdFollowingRequest request, RequestOptions requestOptions) {
        return this.rawClient.listUserFollowing(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingSubIdResponse> getAFollowingFromUser(String id, String subId) {
        return this.rawClient.getAFollowingFromUser(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingSubIdResponse> getAFollowingFromUser(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.getAFollowingFromUser(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingSubIdResponse> getAFollowingFromUser(
            String id, String subId, GetUsersIdFollowingSubIdRequest request) {
        return this.rawClient.getAFollowingFromUser(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetUsersIdFollowingSubIdResponse> getAFollowingFromUser(
            String id, String subId, GetUsersIdFollowingSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAFollowingFromUser(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowingSubIdResponse> deleteAFollowingFromUser(String id, String subId) {
        return this.rawClient.deleteAFollowingFromUser(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowingSubIdResponse> deleteAFollowingFromUser(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient
                .deleteAFollowingFromUser(id, subId, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowingSubIdResponse> deleteAFollowingFromUser(
            String id, String subId, DeleteUsersIdFollowingSubIdRequest request) {
        return this.rawClient.deleteAFollowingFromUser(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteUsersIdFollowingSubIdResponse> deleteAFollowingFromUser(
            String id, String subId, DeleteUsersIdFollowingSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .deleteAFollowingFromUser(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
