/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.tags.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetTagsResponse.Builder.class)
public final class GetTagsResponse {
    private final List<GetTagsResponseDataItem> data;

    private final GetTagsResponseMeta meta;

    private final Map<String, Object> additionalProperties;

    private GetTagsResponse(
            List<GetTagsResponseDataItem> data, GetTagsResponseMeta meta, Map<String, Object> additionalProperties) {
        this.data = data;
        this.meta = meta;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<GetTagsResponseDataItem> getData() {
        return data;
    }

    @JsonProperty("meta")
    public GetTagsResponseMeta getMeta() {
        return meta;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetTagsResponse && equalTo((GetTagsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetTagsResponse other) {
        return data.equals(other.data) && meta.equals(other.meta);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.meta);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MetaStage builder() {
        return new Builder();
    }

    public interface MetaStage {
        _FinalStage meta(@NotNull GetTagsResponseMeta meta);

        Builder from(GetTagsResponse other);
    }

    public interface _FinalStage {
        GetTagsResponse build();

        _FinalStage data(List<GetTagsResponseDataItem> data);

        _FinalStage addData(GetTagsResponseDataItem data);

        _FinalStage addAllData(List<GetTagsResponseDataItem> data);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MetaStage, _FinalStage {
        private GetTagsResponseMeta meta;

        private List<GetTagsResponseDataItem> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(GetTagsResponse other) {
            data(other.getData());
            meta(other.getMeta());
            return this;
        }

        @java.lang.Override
        @JsonSetter("meta")
        public _FinalStage meta(@NotNull GetTagsResponseMeta meta) {
            this.meta = Objects.requireNonNull(meta, "meta must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<GetTagsResponseDataItem> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(GetTagsResponseDataItem data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<GetTagsResponseDataItem> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public GetTagsResponse build() {
            return new GetTagsResponse(data, meta, additionalProperties);
        }
    }
}
