/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.Nullable;
import com.foru.ms.api.core.NullableNonemptyFilter;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateNotificationsResponseData.Builder.class)
public final class UpdateNotificationsResponseData {
    private final String id;

    private final String userId;

    private final String notifierId;

    private final Optional<String> type;

    private final Optional<String> description;

    private final Optional<String> status;

    private final Optional<String> threadId;

    private final Optional<String> postId;

    private final Optional<String> privateMessageId;

    private final Optional<Map<String, Object>> extendedData;

    private final String createdAt;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private UpdateNotificationsResponseData(
            String id,
            String userId,
            String notifierId,
            Optional<String> type,
            Optional<String> description,
            Optional<String> status,
            Optional<String> threadId,
            Optional<String> postId,
            Optional<String> privateMessageId,
            Optional<Map<String, Object>> extendedData,
            String createdAt,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.userId = userId;
        this.notifierId = notifierId;
        this.type = type;
        this.description = description;
        this.status = status;
        this.threadId = threadId;
        this.postId = postId;
        this.privateMessageId = privateMessageId;
        this.extendedData = extendedData;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return Recipient user ID
     */
    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * @return User ID who triggered the notification
     */
    @JsonProperty("notifierId")
    public String getNotifierId() {
        return notifierId;
    }

    /**
     * @return Notification type
     */
    @JsonIgnore
    public Optional<String> getType() {
        if (type == null) {
            return Optional.empty();
        }
        return type;
    }

    /**
     * @return Notification text content
     */
    @JsonIgnore
    public Optional<String> getDescription() {
        if (description == null) {
            return Optional.empty();
        }
        return description;
    }

    /**
     * @return Notification status (read, unread, dismissed, archived)
     */
    @JsonIgnore
    public Optional<String> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    /**
     * @return Related thread ID
     */
    @JsonIgnore
    public Optional<String> getThreadId() {
        if (threadId == null) {
            return Optional.empty();
        }
        return threadId;
    }

    /**
     * @return Related post ID
     */
    @JsonIgnore
    public Optional<String> getPostId() {
        if (postId == null) {
            return Optional.empty();
        }
        return postId;
    }

    /**
     * @return Related private message ID
     */
    @JsonIgnore
    public Optional<String> getPrivateMessageId() {
        if (privateMessageId == null) {
            return Optional.empty();
        }
        return privateMessageId;
    }

    /**
     * @return Additional notification data
     */
    @JsonIgnore
    public Optional<Map<String, Object>> getExtendedData() {
        if (extendedData == null) {
            return Optional.empty();
        }
        return extendedData;
    }

    /**
     * @return Notification creation timestamp
     */
    @JsonProperty("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Notification last update timestamp
     */
    @JsonProperty("updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private Optional<String> _getType() {
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("description")
    private Optional<String> _getDescription() {
        return description;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("status")
    private Optional<String> _getStatus() {
        return status;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("threadId")
    private Optional<String> _getThreadId() {
        return threadId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("postId")
    private Optional<String> _getPostId() {
        return postId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("privateMessageId")
    private Optional<String> _getPrivateMessageId() {
        return privateMessageId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("extendedData")
    private Optional<Map<String, Object>> _getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateNotificationsResponseData && equalTo((UpdateNotificationsResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateNotificationsResponseData other) {
        return id.equals(other.id)
                && userId.equals(other.userId)
                && notifierId.equals(other.notifierId)
                && type.equals(other.type)
                && description.equals(other.description)
                && status.equals(other.status)
                && threadId.equals(other.threadId)
                && postId.equals(other.postId)
                && privateMessageId.equals(other.privateMessageId)
                && extendedData.equals(other.extendedData)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.userId,
                this.notifierId,
                this.type,
                this.description,
                this.status,
                this.threadId,
                this.postId,
                this.privateMessageId,
                this.extendedData,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        UserIdStage id(@NotNull String id);

        Builder from(UpdateNotificationsResponseData other);
    }

    public interface UserIdStage {
        /**
         * <p>Recipient user ID</p>
         */
        NotifierIdStage userId(@NotNull String userId);
    }

    public interface NotifierIdStage {
        /**
         * <p>User ID who triggered the notification</p>
         */
        CreatedAtStage notifierId(@NotNull String notifierId);
    }

    public interface CreatedAtStage {
        /**
         * <p>Notification creation timestamp</p>
         */
        UpdatedAtStage createdAt(@NotNull String createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>Notification last update timestamp</p>
         */
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        UpdateNotificationsResponseData build();

        /**
         * <p>Notification type</p>
         */
        _FinalStage type(Optional<String> type);

        _FinalStage type(String type);

        _FinalStage type(Nullable<String> type);

        /**
         * <p>Notification text content</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        _FinalStage description(Nullable<String> description);

        /**
         * <p>Notification status (read, unread, dismissed, archived)</p>
         */
        _FinalStage status(Optional<String> status);

        _FinalStage status(String status);

        _FinalStage status(Nullable<String> status);

        /**
         * <p>Related thread ID</p>
         */
        _FinalStage threadId(Optional<String> threadId);

        _FinalStage threadId(String threadId);

        _FinalStage threadId(Nullable<String> threadId);

        /**
         * <p>Related post ID</p>
         */
        _FinalStage postId(Optional<String> postId);

        _FinalStage postId(String postId);

        _FinalStage postId(Nullable<String> postId);

        /**
         * <p>Related private message ID</p>
         */
        _FinalStage privateMessageId(Optional<String> privateMessageId);

        _FinalStage privateMessageId(String privateMessageId);

        _FinalStage privateMessageId(Nullable<String> privateMessageId);

        /**
         * <p>Additional notification data</p>
         */
        _FinalStage extendedData(Optional<Map<String, Object>> extendedData);

        _FinalStage extendedData(Map<String, Object> extendedData);

        _FinalStage extendedData(Nullable<Map<String, Object>> extendedData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, UserIdStage, NotifierIdStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String userId;

        private String notifierId;

        private String createdAt;

        private String updatedAt;

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        private Optional<String> privateMessageId = Optional.empty();

        private Optional<String> postId = Optional.empty();

        private Optional<String> threadId = Optional.empty();

        private Optional<String> status = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateNotificationsResponseData other) {
            id(other.getId());
            userId(other.getUserId());
            notifierId(other.getNotifierId());
            type(other.getType());
            description(other.getDescription());
            status(other.getStatus());
            threadId(other.getThreadId());
            postId(other.getPostId());
            privateMessageId(other.getPrivateMessageId());
            extendedData(other.getExtendedData());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public UserIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>Recipient user ID</p>
         * <p>Recipient user ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("userId")
        public NotifierIdStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        /**
         * <p>User ID who triggered the notification</p>
         * <p>User ID who triggered the notification</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("notifierId")
        public CreatedAtStage notifierId(@NotNull String notifierId) {
            this.notifierId = Objects.requireNonNull(notifierId, "notifierId must not be null");
            return this;
        }

        /**
         * <p>Notification creation timestamp</p>
         * <p>Notification creation timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>Notification last update timestamp</p>
         * <p>Notification last update timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        /**
         * <p>Additional notification data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Nullable<Map<String, Object>> extendedData) {
            if (extendedData.isNull()) {
                this.extendedData = null;
            } else if (extendedData.isEmpty()) {
                this.extendedData = Optional.empty();
            } else {
                this.extendedData = Optional.of(extendedData.get());
            }
            return this;
        }

        /**
         * <p>Additional notification data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        /**
         * <p>Additional notification data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public _FinalStage extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        /**
         * <p>Related private message ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privateMessageId(Nullable<String> privateMessageId) {
            if (privateMessageId.isNull()) {
                this.privateMessageId = null;
            } else if (privateMessageId.isEmpty()) {
                this.privateMessageId = Optional.empty();
            } else {
                this.privateMessageId = Optional.of(privateMessageId.get());
            }
            return this;
        }

        /**
         * <p>Related private message ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privateMessageId(String privateMessageId) {
            this.privateMessageId = Optional.ofNullable(privateMessageId);
            return this;
        }

        /**
         * <p>Related private message ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "privateMessageId", nulls = Nulls.SKIP)
        public _FinalStage privateMessageId(Optional<String> privateMessageId) {
            this.privateMessageId = privateMessageId;
            return this;
        }

        /**
         * <p>Related post ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage postId(Nullable<String> postId) {
            if (postId.isNull()) {
                this.postId = null;
            } else if (postId.isEmpty()) {
                this.postId = Optional.empty();
            } else {
                this.postId = Optional.of(postId.get());
            }
            return this;
        }

        /**
         * <p>Related post ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage postId(String postId) {
            this.postId = Optional.ofNullable(postId);
            return this;
        }

        /**
         * <p>Related post ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "postId", nulls = Nulls.SKIP)
        public _FinalStage postId(Optional<String> postId) {
            this.postId = postId;
            return this;
        }

        /**
         * <p>Related thread ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage threadId(Nullable<String> threadId) {
            if (threadId.isNull()) {
                this.threadId = null;
            } else if (threadId.isEmpty()) {
                this.threadId = Optional.empty();
            } else {
                this.threadId = Optional.of(threadId.get());
            }
            return this;
        }

        /**
         * <p>Related thread ID</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage threadId(String threadId) {
            this.threadId = Optional.ofNullable(threadId);
            return this;
        }

        /**
         * <p>Related thread ID</p>
         */
        @java.lang.Override
        @JsonSetter(value = "threadId", nulls = Nulls.SKIP)
        public _FinalStage threadId(Optional<String> threadId) {
            this.threadId = threadId;
            return this;
        }

        /**
         * <p>Notification status (read, unread, dismissed, archived)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(Nullable<String> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        /**
         * <p>Notification status (read, unread, dismissed, archived)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(String status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Notification status (read, unread, dismissed, archived)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<String> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Notification text content</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(Nullable<String> description) {
            if (description.isNull()) {
                this.description = null;
            } else if (description.isEmpty()) {
                this.description = Optional.empty();
            } else {
                this.description = Optional.of(description.get());
            }
            return this;
        }

        /**
         * <p>Notification text content</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Notification text content</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        /**
         * <p>Notification type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(Nullable<String> type) {
            if (type.isNull()) {
                this.type = null;
            } else if (type.isEmpty()) {
                this.type = Optional.empty();
            } else {
                this.type = Optional.of(type.get());
            }
            return this;
        }

        /**
         * <p>Notification type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>Notification type</p>
         */
        @java.lang.Override
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public _FinalStage type(Optional<String> type) {
            this.type = type;
            return this;
        }

        @java.lang.Override
        public UpdateNotificationsResponseData build() {
            return new UpdateNotificationsResponseData(
                    id,
                    userId,
                    notifierId,
                    type,
                    description,
                    status,
                    threadId,
                    postId,
                    privateMessageId,
                    extendedData,
                    createdAt,
                    updatedAt,
                    additionalProperties);
        }
    }
}
