/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.users.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.resources.users.types.ListUsersRequestSort;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListUsersRequest.Builder.class)
public final class ListUsersRequest {
    private final Optional<Integer> limit;

    private final Optional<String> cursor;

    private final Optional<String> search;

    private final Optional<ListUsersRequestSort> sort;

    private final Map<String, Object> additionalProperties;

    private ListUsersRequest(
            Optional<Integer> limit,
            Optional<String> cursor,
            Optional<String> search,
            Optional<ListUsersRequestSort> sort,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.cursor = cursor;
        this.search = search;
        this.sort = sort;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Items per page (max 75)
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Cursor for pagination
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    /**
     * @return Search by username or display name
     */
    @JsonProperty("search")
    public Optional<String> getSearch() {
        return search;
    }

    /**
     * @return Sort by creation date
     */
    @JsonProperty("sort")
    public Optional<ListUsersRequestSort> getSort() {
        return sort;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListUsersRequest && equalTo((ListUsersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListUsersRequest other) {
        return limit.equals(other.limit)
                && cursor.equals(other.cursor)
                && search.equals(other.search)
                && sort.equals(other.sort);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.limit, this.cursor, this.search, this.sort);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> limit = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Optional<String> search = Optional.empty();

        private Optional<ListUsersRequestSort> sort = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListUsersRequest other) {
            limit(other.getLimit());
            cursor(other.getCursor());
            search(other.getSearch());
            sort(other.getSort());
            return this;
        }

        /**
         * <p>Items per page (max 75)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Cursor for pagination</p>
         */
        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * <p>Search by username or display name</p>
         */
        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(Optional<String> search) {
            this.search = search;
            return this;
        }

        public Builder search(String search) {
            this.search = Optional.ofNullable(search);
            return this;
        }

        /**
         * <p>Sort by creation date</p>
         */
        @JsonSetter(value = "sort", nulls = Nulls.SKIP)
        public Builder sort(Optional<ListUsersRequestSort> sort) {
            this.sort = sort;
            return this;
        }

        public Builder sort(ListUsersRequestSort sort) {
            this.sort = Optional.ofNullable(sort);
            return this;
        }

        public ListUsersRequest build() {
            return new ListUsersRequest(limit, cursor, search, sort, additionalProperties);
        }
    }
}
