/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.search.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchSearchResponseDataItemsItem.Builder.class)
public final class SearchSearchResponseDataItemsItem {
    private final SearchSearchResponseDataItemsItemType type;

    private final String id;

    private final Optional<String> title;

    private final Optional<String> body;

    private final Optional<String> username;

    private final Optional<String> name;

    private final Optional<String> createdAt;

    private final Map<String, Object> additionalProperties;

    private SearchSearchResponseDataItemsItem(
            SearchSearchResponseDataItemsItemType type,
            String id,
            Optional<String> title,
            Optional<String> body,
            Optional<String> username,
            Optional<String> name,
            Optional<String> createdAt,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.id = id;
        this.title = title;
        this.body = body;
        this.username = username;
        this.name = name;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public SearchSearchResponseDataItemsItemType getType() {
        return type;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    @JsonProperty("body")
    public Optional<String> getBody() {
        return body;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        return username;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("createdAt")
    public Optional<String> getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchSearchResponseDataItemsItem && equalTo((SearchSearchResponseDataItemsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchSearchResponseDataItemsItem other) {
        return type.equals(other.type)
                && id.equals(other.id)
                && title.equals(other.title)
                && body.equals(other.body)
                && username.equals(other.username)
                && name.equals(other.name)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.id, this.title, this.body, this.username, this.name, this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        IdStage type(@NotNull SearchSearchResponseDataItemsItemType type);

        Builder from(SearchSearchResponseDataItemsItem other);
    }

    public interface IdStage {
        _FinalStage id(@NotNull String id);
    }

    public interface _FinalStage {
        SearchSearchResponseDataItemsItem build();

        _FinalStage title(Optional<String> title);

        _FinalStage title(String title);

        _FinalStage body(Optional<String> body);

        _FinalStage body(String body);

        _FinalStage username(Optional<String> username);

        _FinalStage username(String username);

        _FinalStage name(Optional<String> name);

        _FinalStage name(String name);

        _FinalStage createdAt(Optional<String> createdAt);

        _FinalStage createdAt(String createdAt);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, IdStage, _FinalStage {
        private SearchSearchResponseDataItemsItemType type;

        private String id;

        private Optional<String> createdAt = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> username = Optional.empty();

        private Optional<String> body = Optional.empty();

        private Optional<String> title = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SearchSearchResponseDataItemsItem other) {
            type(other.getType());
            id(other.getId());
            title(other.getTitle());
            body(other.getBody());
            username(other.getUsername());
            name(other.getName());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public IdStage type(@NotNull SearchSearchResponseDataItemsItemType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public _FinalStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage createdAt(String createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "createdAt", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<String> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public _FinalStage name(Optional<String> name) {
            this.name = name;
            return this;
        }

        @java.lang.Override
        public _FinalStage username(String username) {
            this.username = Optional.ofNullable(username);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public _FinalStage username(Optional<String> username) {
            this.username = username;
            return this;
        }

        @java.lang.Override
        public _FinalStage body(String body) {
            this.body = Optional.ofNullable(body);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public _FinalStage body(Optional<String> body) {
            this.body = body;
            return this;
        }

        @java.lang.Override
        public _FinalStage title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public _FinalStage title(Optional<String> title) {
            this.title = title;
            return this;
        }

        @java.lang.Override
        public SearchSearchResponseDataItemsItem build() {
            return new SearchSearchResponseDataItemsItem(
                    type, id, title, body, username, name, createdAt, additionalProperties);
        }
    }
}
