/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.reports;

import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.resources.reports.requests.CreateReportsRequest;
import com.foru.ms.api.resources.reports.requests.DeleteReportsRequest;
import com.foru.ms.api.resources.reports.requests.ListReportsRequest;
import com.foru.ms.api.resources.reports.requests.RetrieveReportsRequest;
import com.foru.ms.api.resources.reports.requests.UpdateReportsRequest;
import com.foru.ms.api.resources.reports.types.UpdateReportsResponse;
import com.foru.ms.api.types.ReportListResponse;
import com.foru.ms.api.types.ReportResponse;
import com.foru.ms.api.types.SuccessResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncReportsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawReportsClient rawClient;

    public AsyncReportsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawReportsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawReportsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a paginated list of reports. Use cursor for pagination.
     */
    public CompletableFuture<ReportListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of reports. Use cursor for pagination.
     */
    public CompletableFuture<ReportListResponse> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of reports. Use cursor for pagination.
     */
    public CompletableFuture<ReportListResponse> list(ListReportsRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of reports. Use cursor for pagination.
     */
    public CompletableFuture<ReportListResponse> list(ListReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a new report.
     */
    public CompletableFuture<ReportResponse> create(CreateReportsRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create a new report.
     */
    public CompletableFuture<ReportResponse> create(CreateReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a report by ID or slug (if supported).
     */
    public CompletableFuture<ReportResponse> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve a report by ID or slug (if supported).
     */
    public CompletableFuture<ReportResponse> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a report by ID or slug (if supported).
     */
    public CompletableFuture<ReportResponse> retrieve(String id, RetrieveReportsRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a report by ID or slug (if supported).
     */
    public CompletableFuture<ReportResponse> retrieve(
            String id, RetrieveReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently delete a report.
     */
    public CompletableFuture<SuccessResponse> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Permanently delete a report.
     */
    public CompletableFuture<SuccessResponse> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently delete a report.
     */
    public CompletableFuture<SuccessResponse> delete(String id, DeleteReportsRequest request) {
        return this.rawClient.delete(id, request).thenApply(response -> response.body());
    }

    /**
     * Permanently delete a report.
     */
    public CompletableFuture<SuccessResponse> delete(
            String id, DeleteReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an existing report. Only provided fields will be modified.
     */
    public CompletableFuture<UpdateReportsResponse> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Update an existing report. Only provided fields will be modified.
     */
    public CompletableFuture<UpdateReportsResponse> update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an existing report. Only provided fields will be modified.
     */
    public CompletableFuture<UpdateReportsResponse> update(String id, UpdateReportsRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Update an existing report. Only provided fields will be modified.
     */
    public CompletableFuture<UpdateReportsResponse> update(
            String id, UpdateReportsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }
}
