/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.threads.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.Nullable;
import com.foru.ms.api.core.NullableNonemptyFilter;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RetrievePostThreadsResponseData.Builder.class)
public final class RetrievePostThreadsResponseData {
    private final String id;

    private final String threadId;

    private final String userId;

    private final String body;

    private final Optional<Integer> depth;

    private final Optional<RetrievePostThreadsResponseDataUser> user;

    private final Optional<RetrievePostThreadsResponseDataCount> count;

    private final String createdAt;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private RetrievePostThreadsResponseData(
            String id,
            String threadId,
            String userId,
            String body,
            Optional<Integer> depth,
            Optional<RetrievePostThreadsResponseDataUser> user,
            Optional<RetrievePostThreadsResponseDataCount> count,
            String createdAt,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.threadId = threadId;
        this.userId = userId;
        this.body = body;
        this.depth = depth;
        this.user = user;
        this.count = count;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("threadId")
    public String getThreadId() {
        return threadId;
    }

    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    @JsonProperty("body")
    public String getBody() {
        return body;
    }

    @JsonIgnore
    public Optional<Integer> getDepth() {
        if (depth == null) {
            return Optional.empty();
        }
        return depth;
    }

    @JsonProperty("user")
    public Optional<RetrievePostThreadsResponseDataUser> getUser() {
        return user;
    }

    @JsonProperty("_count")
    public Optional<RetrievePostThreadsResponseDataCount> getCount() {
        return count;
    }

    @JsonProperty("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("depth")
    private Optional<Integer> _getDepth() {
        return depth;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RetrievePostThreadsResponseData && equalTo((RetrievePostThreadsResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RetrievePostThreadsResponseData other) {
        return id.equals(other.id)
                && threadId.equals(other.threadId)
                && userId.equals(other.userId)
                && body.equals(other.body)
                && depth.equals(other.depth)
                && user.equals(other.user)
                && count.equals(other.count)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.threadId,
                this.userId,
                this.body,
                this.depth,
                this.user,
                this.count,
                this.createdAt,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        ThreadIdStage id(@NotNull String id);

        Builder from(RetrievePostThreadsResponseData other);
    }

    public interface ThreadIdStage {
        UserIdStage threadId(@NotNull String threadId);
    }

    public interface UserIdStage {
        BodyStage userId(@NotNull String userId);
    }

    public interface BodyStage {
        CreatedAtStage body(@NotNull String body);
    }

    public interface CreatedAtStage {
        UpdatedAtStage createdAt(@NotNull String createdAt);
    }

    public interface UpdatedAtStage {
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        RetrievePostThreadsResponseData build();

        _FinalStage depth(Optional<Integer> depth);

        _FinalStage depth(Integer depth);

        _FinalStage depth(Nullable<Integer> depth);

        _FinalStage user(Optional<RetrievePostThreadsResponseDataUser> user);

        _FinalStage user(RetrievePostThreadsResponseDataUser user);

        _FinalStage count(Optional<RetrievePostThreadsResponseDataCount> count);

        _FinalStage count(RetrievePostThreadsResponseDataCount count);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, ThreadIdStage, UserIdStage, BodyStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String threadId;

        private String userId;

        private String body;

        private String createdAt;

        private String updatedAt;

        private Optional<RetrievePostThreadsResponseDataCount> count = Optional.empty();

        private Optional<RetrievePostThreadsResponseDataUser> user = Optional.empty();

        private Optional<Integer> depth = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RetrievePostThreadsResponseData other) {
            id(other.getId());
            threadId(other.getThreadId());
            userId(other.getUserId());
            body(other.getBody());
            depth(other.getDepth());
            user(other.getUser());
            count(other.getCount());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ThreadIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("threadId")
        public UserIdStage threadId(@NotNull String threadId) {
            this.threadId = Objects.requireNonNull(threadId, "threadId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("userId")
        public BodyStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("body")
        public CreatedAtStage body(@NotNull String body) {
            this.body = Objects.requireNonNull(body, "body must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage count(RetrievePostThreadsResponseDataCount count) {
            this.count = Optional.ofNullable(count);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "_count", nulls = Nulls.SKIP)
        public _FinalStage count(Optional<RetrievePostThreadsResponseDataCount> count) {
            this.count = count;
            return this;
        }

        @java.lang.Override
        public _FinalStage user(RetrievePostThreadsResponseDataUser user) {
            this.user = Optional.ofNullable(user);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user", nulls = Nulls.SKIP)
        public _FinalStage user(Optional<RetrievePostThreadsResponseDataUser> user) {
            this.user = user;
            return this;
        }

        @java.lang.Override
        public _FinalStage depth(Nullable<Integer> depth) {
            if (depth.isNull()) {
                this.depth = null;
            } else if (depth.isEmpty()) {
                this.depth = Optional.empty();
            } else {
                this.depth = Optional.of(depth.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage depth(Integer depth) {
            this.depth = Optional.ofNullable(depth);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "depth", nulls = Nulls.SKIP)
        public _FinalStage depth(Optional<Integer> depth) {
            this.depth = depth;
            return this;
        }

        @java.lang.Override
        public RetrievePostThreadsResponseData build() {
            return new RetrievePostThreadsResponseData(
                    id, threadId, userId, body, depth, user, count, createdAt, updatedAt, additionalProperties);
        }
    }
}
