/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.posts;

import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.resources.posts.requests.DeletePostsIdPostsSubIdRequest;
import com.foru.ms.api.resources.posts.requests.DeletePostsIdReactionsRequest;
import com.foru.ms.api.resources.posts.requests.DeletePostsIdReactionsSubIdRequest;
import com.foru.ms.api.resources.posts.requests.DeletePostsIdRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsIdPostsRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsIdPostsSubIdRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsIdReactionsRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsIdReactionsSubIdRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsIdRequest;
import com.foru.ms.api.resources.posts.requests.GetPostsRequest;
import com.foru.ms.api.resources.posts.requests.PatchPostsIdRequest;
import com.foru.ms.api.resources.posts.requests.PostPostsIdReactionsRequest;
import com.foru.ms.api.resources.posts.requests.PostPostsRequest;
import com.foru.ms.api.resources.posts.types.DeletePostsIdPostsSubIdResponse;
import com.foru.ms.api.resources.posts.types.DeletePostsIdReactionsResponse;
import com.foru.ms.api.resources.posts.types.DeletePostsIdReactionsSubIdResponse;
import com.foru.ms.api.resources.posts.types.DeletePostsIdResponse;
import com.foru.ms.api.resources.posts.types.GetPostsIdPostsResponse;
import com.foru.ms.api.resources.posts.types.GetPostsIdPostsSubIdResponse;
import com.foru.ms.api.resources.posts.types.GetPostsIdReactionsResponse;
import com.foru.ms.api.resources.posts.types.GetPostsIdReactionsSubIdResponse;
import com.foru.ms.api.resources.posts.types.GetPostsIdResponse;
import com.foru.ms.api.resources.posts.types.GetPostsResponse;
import com.foru.ms.api.resources.posts.types.PatchPostsIdResponse;
import com.foru.ms.api.resources.posts.types.PostPostsIdReactionsResponse;
import com.foru.ms.api.resources.posts.types.PostPostsResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncPostsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPostsClient rawClient;

    public AsyncPostsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPostsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPostsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<GetPostsResponse> listAllPosts() {
        return this.rawClient.listAllPosts().thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsResponse> listAllPosts(RequestOptions requestOptions) {
        return this.rawClient.listAllPosts(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsResponse> listAllPosts(GetPostsRequest request) {
        return this.rawClient.listAllPosts(request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsResponse> listAllPosts(GetPostsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAllPosts(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PostPostsResponse> createAPost(PostPostsRequest request) {
        return this.rawClient.createAPost(request).thenApply(response -> response.body());
    }

    public CompletableFuture<PostPostsResponse> createAPost(PostPostsRequest request, RequestOptions requestOptions) {
        return this.rawClient.createAPost(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdResponse> getAPost(String id) {
        return this.rawClient.getAPost(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdResponse> getAPost(String id, RequestOptions requestOptions) {
        return this.rawClient.getAPost(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdResponse> getAPost(String id, GetPostsIdRequest request) {
        return this.rawClient.getAPost(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdResponse> getAPost(
            String id, GetPostsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAPost(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdResponse> deleteAPost(String id) {
        return this.rawClient.deleteAPost(id).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdResponse> deleteAPost(String id, RequestOptions requestOptions) {
        return this.rawClient.deleteAPost(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdResponse> deleteAPost(String id, DeletePostsIdRequest request) {
        return this.rawClient.deleteAPost(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdResponse> deleteAPost(
            String id, DeletePostsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteAPost(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchPostsIdResponse> updateAPost(String id) {
        return this.rawClient.updateAPost(id).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchPostsIdResponse> updateAPost(String id, RequestOptions requestOptions) {
        return this.rawClient.updateAPost(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchPostsIdResponse> updateAPost(String id, PatchPostsIdRequest request) {
        return this.rawClient.updateAPost(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<PatchPostsIdResponse> updateAPost(
            String id, PatchPostsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateAPost(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsResponse> listPostReactions(String id) {
        return this.rawClient.listPostReactions(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsResponse> listPostReactions(String id, RequestOptions requestOptions) {
        return this.rawClient.listPostReactions(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsResponse> listPostReactions(
            String id, GetPostsIdReactionsRequest request) {
        return this.rawClient.listPostReactions(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsResponse> listPostReactions(
            String id, GetPostsIdReactionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPostReactions(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PostPostsIdReactionsResponse> createAReactionInPost(
            String id, PostPostsIdReactionsRequest request) {
        return this.rawClient.createAReactionInPost(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<PostPostsIdReactionsResponse> createAReactionInPost(
            String id, PostPostsIdReactionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.createAReactionInPost(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Removes the authenticated user's reaction. No subId needed.
     */
    public CompletableFuture<DeletePostsIdReactionsResponse> removeYourReactionFromPost(String id) {
        return this.rawClient.removeYourReactionFromPost(id).thenApply(response -> response.body());
    }

    /**
     * Removes the authenticated user's reaction. No subId needed.
     */
    public CompletableFuture<DeletePostsIdReactionsResponse> removeYourReactionFromPost(
            String id, RequestOptions requestOptions) {
        return this.rawClient.removeYourReactionFromPost(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Removes the authenticated user's reaction. No subId needed.
     */
    public CompletableFuture<DeletePostsIdReactionsResponse> removeYourReactionFromPost(
            String id, DeletePostsIdReactionsRequest request) {
        return this.rawClient.removeYourReactionFromPost(id, request).thenApply(response -> response.body());
    }

    /**
     * Removes the authenticated user's reaction. No subId needed.
     */
    public CompletableFuture<DeletePostsIdReactionsResponse> removeYourReactionFromPost(
            String id, DeletePostsIdReactionsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .removeYourReactionFromPost(id, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsSubIdResponse> getAReactionFromPost(String id, String subId) {
        return this.rawClient.getAReactionFromPost(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsSubIdResponse> getAReactionFromPost(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.getAReactionFromPost(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsSubIdResponse> getAReactionFromPost(
            String id, String subId, GetPostsIdReactionsSubIdRequest request) {
        return this.rawClient.getAReactionFromPost(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdReactionsSubIdResponse> getAReactionFromPost(
            String id, String subId, GetPostsIdReactionsSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAReactionFromPost(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdReactionsSubIdResponse> deleteAReactionFromPost(String id, String subId) {
        return this.rawClient.deleteAReactionFromPost(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdReactionsSubIdResponse> deleteAReactionFromPost(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.deleteAReactionFromPost(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdReactionsSubIdResponse> deleteAReactionFromPost(
            String id, String subId, DeletePostsIdReactionsSubIdRequest request) {
        return this.rawClient.deleteAReactionFromPost(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdReactionsSubIdResponse> deleteAReactionFromPost(
            String id, String subId, DeletePostsIdReactionsSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .deleteAReactionFromPost(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsResponse> listPostPosts(String id) {
        return this.rawClient.listPostPosts(id).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsResponse> listPostPosts(String id, RequestOptions requestOptions) {
        return this.rawClient.listPostPosts(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsResponse> listPostPosts(String id, GetPostsIdPostsRequest request) {
        return this.rawClient.listPostPosts(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsResponse> listPostPosts(
            String id, GetPostsIdPostsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPostPosts(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsSubIdResponse> getAPostFromPost(String id, String subId) {
        return this.rawClient.getAPostFromPost(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsSubIdResponse> getAPostFromPost(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.getAPostFromPost(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsSubIdResponse> getAPostFromPost(
            String id, String subId, GetPostsIdPostsSubIdRequest request) {
        return this.rawClient.getAPostFromPost(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<GetPostsIdPostsSubIdResponse> getAPostFromPost(
            String id, String subId, GetPostsIdPostsSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getAPostFromPost(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdPostsSubIdResponse> deleteAPostFromPost(String id, String subId) {
        return this.rawClient.deleteAPostFromPost(id, subId).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdPostsSubIdResponse> deleteAPostFromPost(
            String id, String subId, RequestOptions requestOptions) {
        return this.rawClient.deleteAPostFromPost(id, subId, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdPostsSubIdResponse> deleteAPostFromPost(
            String id, String subId, DeletePostsIdPostsSubIdRequest request) {
        return this.rawClient.deleteAPostFromPost(id, subId, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeletePostsIdPostsSubIdResponse> deleteAPostFromPost(
            String id, String subId, DeletePostsIdPostsSubIdRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .deleteAPostFromPost(id, subId, request, requestOptions)
                .thenApply(response -> response.body());
    }
}
