/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.provisioning.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ChangePlanProvisioningResponseData.Builder.class)
public final class ChangePlanProvisioningResponseData {
    private final ChangePlanProvisioningResponseDataAction action;

    private final Optional<String> plan;

    private final Optional<Boolean> isAnnual;

    private final Optional<String> message;

    private final String url;

    private final Map<String, Object> additionalProperties;

    private ChangePlanProvisioningResponseData(
            ChangePlanProvisioningResponseDataAction action,
            Optional<String> plan,
            Optional<Boolean> isAnnual,
            Optional<String> message,
            String url,
            Map<String, Object> additionalProperties) {
        this.action = action;
        this.plan = plan;
        this.isAnnual = isAnnual;
        this.message = message;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("action")
    public ChangePlanProvisioningResponseDataAction getAction() {
        return action;
    }

    @JsonProperty("plan")
    public Optional<String> getPlan() {
        return plan;
    }

    @JsonProperty("isAnnual")
    public Optional<Boolean> getIsAnnual() {
        return isAnnual;
    }

    @JsonProperty("message")
    public Optional<String> getMessage() {
        return message;
    }

    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChangePlanProvisioningResponseData
                && equalTo((ChangePlanProvisioningResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChangePlanProvisioningResponseData other) {
        return action.equals(other.action)
                && plan.equals(other.plan)
                && isAnnual.equals(other.isAnnual)
                && message.equals(other.message)
                && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.action, this.plan, this.isAnnual, this.message, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActionStage builder() {
        return new Builder();
    }

    public interface ActionStage {
        UrlStage action(@NotNull ChangePlanProvisioningResponseDataAction action);

        Builder from(ChangePlanProvisioningResponseData other);
    }

    public interface UrlStage {
        _FinalStage url(@NotNull String url);
    }

    public interface _FinalStage {
        ChangePlanProvisioningResponseData build();

        _FinalStage plan(Optional<String> plan);

        _FinalStage plan(String plan);

        _FinalStage isAnnual(Optional<Boolean> isAnnual);

        _FinalStage isAnnual(Boolean isAnnual);

        _FinalStage message(Optional<String> message);

        _FinalStage message(String message);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActionStage, UrlStage, _FinalStage {
        private ChangePlanProvisioningResponseDataAction action;

        private String url;

        private Optional<String> message = Optional.empty();

        private Optional<Boolean> isAnnual = Optional.empty();

        private Optional<String> plan = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ChangePlanProvisioningResponseData other) {
            action(other.getAction());
            plan(other.getPlan());
            isAnnual(other.getIsAnnual());
            message(other.getMessage());
            url(other.getUrl());
            return this;
        }

        @java.lang.Override
        @JsonSetter("action")
        public UrlStage action(@NotNull ChangePlanProvisioningResponseDataAction action) {
            this.action = Objects.requireNonNull(action, "action must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("url")
        public _FinalStage url(@NotNull String url) {
            this.url = Objects.requireNonNull(url, "url must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public _FinalStage message(Optional<String> message) {
            this.message = message;
            return this;
        }

        @java.lang.Override
        public _FinalStage isAnnual(Boolean isAnnual) {
            this.isAnnual = Optional.ofNullable(isAnnual);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "isAnnual", nulls = Nulls.SKIP)
        public _FinalStage isAnnual(Optional<Boolean> isAnnual) {
            this.isAnnual = isAnnual;
            return this;
        }

        @java.lang.Override
        public _FinalStage plan(String plan) {
            this.plan = Optional.ofNullable(plan);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "plan", nulls = Nulls.SKIP)
        public _FinalStage plan(Optional<String> plan) {
            this.plan = plan;
            return this;
        }

        @java.lang.Override
        public ChangePlanProvisioningResponseData build() {
            return new ChangePlanProvisioningResponseData(action, plan, isAnnual, message, url, additionalProperties);
        }
    }
}
