/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.provisioning.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeleteProvisioningResponseData.Builder.class)
public final class DeleteProvisioningResponseData {
    private final String deleted;

    private final Map<String, Object> additionalProperties;

    private DeleteProvisioningResponseData(String deleted, Map<String, Object> additionalProperties) {
        this.deleted = deleted;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("deleted")
    public String getDeleted() {
        return deleted;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeleteProvisioningResponseData && equalTo((DeleteProvisioningResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeleteProvisioningResponseData other) {
        return deleted.equals(other.deleted);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.deleted);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DeletedStage builder() {
        return new Builder();
    }

    public interface DeletedStage {
        _FinalStage deleted(@NotNull String deleted);

        Builder from(DeleteProvisioningResponseData other);
    }

    public interface _FinalStage {
        DeleteProvisioningResponseData build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DeletedStage, _FinalStage {
        private String deleted;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(DeleteProvisioningResponseData other) {
            deleted(other.getDeleted());
            return this;
        }

        @java.lang.Override
        @JsonSetter("deleted")
        public _FinalStage deleted(@NotNull String deleted) {
            this.deleted = Objects.requireNonNull(deleted, "deleted must not be null");
            return this;
        }

        @java.lang.Override
        public DeleteProvisioningResponseData build() {
            return new DeleteProvisioningResponseData(deleted, additionalProperties);
        }
    }
}
