/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.provisioning.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.types.InstanceDomain;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListDomainsProvisioningResponseData.Builder.class)
public final class ListDomainsProvisioningResponseData {
    private final String handle;

    private final List<InstanceDomain> domains;

    private final Map<String, Object> additionalProperties;

    private ListDomainsProvisioningResponseData(
            String handle, List<InstanceDomain> domains, Map<String, Object> additionalProperties) {
        this.handle = handle;
        this.domains = domains;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("handle")
    public String getHandle() {
        return handle;
    }

    @JsonProperty("domains")
    public List<InstanceDomain> getDomains() {
        return domains;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListDomainsProvisioningResponseData
                && equalTo((ListDomainsProvisioningResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListDomainsProvisioningResponseData other) {
        return handle.equals(other.handle) && domains.equals(other.domains);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.handle, this.domains);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static HandleStage builder() {
        return new Builder();
    }

    public interface HandleStage {
        _FinalStage handle(@NotNull String handle);

        Builder from(ListDomainsProvisioningResponseData other);
    }

    public interface _FinalStage {
        ListDomainsProvisioningResponseData build();

        _FinalStage domains(List<InstanceDomain> domains);

        _FinalStage addDomains(InstanceDomain domains);

        _FinalStage addAllDomains(List<InstanceDomain> domains);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements HandleStage, _FinalStage {
        private String handle;

        private List<InstanceDomain> domains = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListDomainsProvisioningResponseData other) {
            handle(other.getHandle());
            domains(other.getDomains());
            return this;
        }

        @java.lang.Override
        @JsonSetter("handle")
        public _FinalStage handle(@NotNull String handle) {
            this.handle = Objects.requireNonNull(handle, "handle must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllDomains(List<InstanceDomain> domains) {
            if (domains != null) {
                this.domains.addAll(domains);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addDomains(InstanceDomain domains) {
            this.domains.add(domains);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "domains", nulls = Nulls.SKIP)
        public _FinalStage domains(List<InstanceDomain> domains) {
            this.domains.clear();
            if (domains != null) {
                this.domains.addAll(domains);
            }
            return this;
        }

        @java.lang.Override
        public ListDomainsProvisioningResponseData build() {
            return new ListDomainsProvisioningResponseData(handle, domains, additionalProperties);
        }
    }
}
