/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.ssos.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostSsoResponseData.Builder.class)
public final class PostSsoResponseData {
    private final String id;

    private final PostSsoResponseDataProvider provider;

    private final String domain;

    private final boolean active;

    private final String createdAt;

    private final String updatedAt;

    private final Map<String, Object> additionalProperties;

    private PostSsoResponseData(
            String id,
            PostSsoResponseDataProvider provider,
            String domain,
            boolean active,
            String createdAt,
            String updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.provider = provider;
        this.domain = domain;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return SSO provider type
     */
    @JsonProperty("provider")
    public PostSsoResponseDataProvider getProvider() {
        return provider;
    }

    /**
     * @return Email domain for this provider
     */
    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    /**
     * @return Whether SSO is active
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    /**
     * @return SSO configuration creation timestamp
     */
    @JsonProperty("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * @return SSO configuration last update timestamp
     */
    @JsonProperty("updatedAt")
    public String getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostSsoResponseData && equalTo((PostSsoResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostSsoResponseData other) {
        return id.equals(other.id)
                && provider.equals(other.provider)
                && domain.equals(other.domain)
                && active == other.active
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.provider, this.domain, this.active, this.createdAt, this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        ProviderStage id(@NotNull String id);

        Builder from(PostSsoResponseData other);
    }

    public interface ProviderStage {
        /**
         * <p>SSO provider type</p>
         */
        DomainStage provider(@NotNull PostSsoResponseDataProvider provider);
    }

    public interface DomainStage {
        /**
         * <p>Email domain for this provider</p>
         */
        ActiveStage domain(@NotNull String domain);
    }

    public interface ActiveStage {
        /**
         * <p>Whether SSO is active</p>
         */
        CreatedAtStage active(boolean active);
    }

    public interface CreatedAtStage {
        /**
         * <p>SSO configuration creation timestamp</p>
         */
        UpdatedAtStage createdAt(@NotNull String createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>SSO configuration last update timestamp</p>
         */
        _FinalStage updatedAt(@NotNull String updatedAt);
    }

    public interface _FinalStage {
        PostSsoResponseData build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, ProviderStage, DomainStage, ActiveStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private PostSsoResponseDataProvider provider;

        private String domain;

        private boolean active;

        private String createdAt;

        private String updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostSsoResponseData other) {
            id(other.getId());
            provider(other.getProvider());
            domain(other.getDomain());
            active(other.getActive());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ProviderStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>SSO provider type</p>
         * <p>SSO provider type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("provider")
        public DomainStage provider(@NotNull PostSsoResponseDataProvider provider) {
            this.provider = Objects.requireNonNull(provider, "provider must not be null");
            return this;
        }

        /**
         * <p>Email domain for this provider</p>
         * <p>Email domain for this provider</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public ActiveStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        /**
         * <p>Whether SSO is active</p>
         * <p>Whether SSO is active</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public CreatedAtStage active(boolean active) {
            this.active = active;
            return this;
        }

        /**
         * <p>SSO configuration creation timestamp</p>
         * <p>SSO configuration creation timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("createdAt")
        public UpdatedAtStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        /**
         * <p>SSO configuration last update timestamp</p>
         * <p>SSO configuration last update timestamp</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull String updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public PostSsoResponseData build() {
            return new PostSsoResponseData(id, provider, domain, active, createdAt, updatedAt, additionalProperties);
        }
    }
}
