/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.webhooks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateWebhooksRequest.Builder.class)
public final class CreateWebhooksRequest {
    private final String name;

    private final String url;

    private final List<String> events;

    private final Optional<String> secret;

    private final Optional<Boolean> active;

    private final Optional<Map<String, Object>> extendedData;

    private final Map<String, Object> additionalProperties;

    private CreateWebhooksRequest(
            String name,
            String url,
            List<String> events,
            Optional<String> secret,
            Optional<Boolean> active,
            Optional<Map<String, Object>> extendedData,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.url = url;
        this.events = events;
        this.secret = secret;
        this.active = active;
        this.extendedData = extendedData;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Webhook name
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Target URL
     */
    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    /**
     * @return List of event types (e.g. post.created)
     */
    @JsonProperty("events")
    public List<String> getEvents() {
        return events;
    }

    /**
     * @return Secret for signature verification (auto-generated if missing)
     */
    @JsonProperty("secret")
    public Optional<String> getSecret() {
        return secret;
    }

    /**
     * @return Whether webhook is active
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Custom extended data
     */
    @JsonProperty("extendedData")
    public Optional<Map<String, Object>> getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateWebhooksRequest && equalTo((CreateWebhooksRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateWebhooksRequest other) {
        return name.equals(other.name)
                && url.equals(other.url)
                && events.equals(other.events)
                && secret.equals(other.secret)
                && active.equals(other.active)
                && extendedData.equals(other.extendedData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.url, this.events, this.secret, this.active, this.extendedData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Webhook name</p>
         */
        UrlStage name(@NotNull String name);

        Builder from(CreateWebhooksRequest other);
    }

    public interface UrlStage {
        /**
         * <p>Target URL</p>
         */
        _FinalStage url(@NotNull String url);
    }

    public interface _FinalStage {
        CreateWebhooksRequest build();

        /**
         * <p>List of event types (e.g. post.created)</p>
         */
        _FinalStage events(List<String> events);

        _FinalStage addEvents(String events);

        _FinalStage addAllEvents(List<String> events);

        /**
         * <p>Secret for signature verification (auto-generated if missing)</p>
         */
        _FinalStage secret(Optional<String> secret);

        _FinalStage secret(String secret);

        /**
         * <p>Whether webhook is active</p>
         */
        _FinalStage active(Optional<Boolean> active);

        _FinalStage active(Boolean active);

        /**
         * <p>Custom extended data</p>
         */
        _FinalStage extendedData(Optional<Map<String, Object>> extendedData);

        _FinalStage extendedData(Map<String, Object> extendedData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, UrlStage, _FinalStage {
        private String name;

        private String url;

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        private Optional<String> secret = Optional.empty();

        private List<String> events = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateWebhooksRequest other) {
            name(other.getName());
            url(other.getUrl());
            events(other.getEvents());
            secret(other.getSecret());
            active(other.getActive());
            extendedData(other.getExtendedData());
            return this;
        }

        /**
         * <p>Webhook name</p>
         * <p>Webhook name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public UrlStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Target URL</p>
         * <p>Target URL</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("url")
        public _FinalStage url(@NotNull String url) {
            this.url = Objects.requireNonNull(url, "url must not be null");
            return this;
        }

        /**
         * <p>Custom extended data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        /**
         * <p>Custom extended data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public _FinalStage extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        /**
         * <p>Whether webhook is active</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Whether webhook is active</p>
         */
        @java.lang.Override
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public _FinalStage active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Secret for signature verification (auto-generated if missing)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage secret(String secret) {
            this.secret = Optional.ofNullable(secret);
            return this;
        }

        /**
         * <p>Secret for signature verification (auto-generated if missing)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "secret", nulls = Nulls.SKIP)
        public _FinalStage secret(Optional<String> secret) {
            this.secret = secret;
            return this;
        }

        /**
         * <p>List of event types (e.g. post.created)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllEvents(List<String> events) {
            if (events != null) {
                this.events.addAll(events);
            }
            return this;
        }

        /**
         * <p>List of event types (e.g. post.created)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addEvents(String events) {
            this.events.add(events);
            return this;
        }

        /**
         * <p>List of event types (e.g. post.created)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "events", nulls = Nulls.SKIP)
        public _FinalStage events(List<String> events) {
            this.events.clear();
            if (events != null) {
                this.events.addAll(events);
            }
            return this;
        }

        @java.lang.Override
        public CreateWebhooksRequest build() {
            return new CreateWebhooksRequest(name, url, events, secret, active, extendedData, additionalProperties);
        }
    }
}
