/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.ssos.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.resources.ssos.types.UpdateSsOsRequestProvider;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateSsOsRequest.Builder.class)
public final class UpdateSsOsRequest {
    private final Optional<UpdateSsOsRequestProvider> provider;

    private final Optional<String> domain;

    private final Optional<Map<String, Object>> config;

    private final Optional<Boolean> active;

    private final Optional<Map<String, Object>> extendedData;

    private final Map<String, Object> additionalProperties;

    private UpdateSsOsRequest(
            Optional<UpdateSsOsRequestProvider> provider,
            Optional<String> domain,
            Optional<Map<String, Object>> config,
            Optional<Boolean> active,
            Optional<Map<String, Object>> extendedData,
            Map<String, Object> additionalProperties) {
        this.provider = provider;
        this.domain = domain;
        this.config = config;
        this.active = active;
        this.extendedData = extendedData;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return SSO provider type
     */
    @JsonProperty("provider")
    public Optional<UpdateSsOsRequestProvider> getProvider() {
        return provider;
    }

    /**
     * @return Email domain to match
     */
    @JsonProperty("domain")
    public Optional<String> getDomain() {
        return domain;
    }

    /**
     * @return Provider configuration
     */
    @JsonProperty("config")
    public Optional<Map<String, Object>> getConfig() {
        return config;
    }

    /**
     * @return Enable/disable provider
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Custom extended data
     */
    @JsonProperty("extendedData")
    public Optional<Map<String, Object>> getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateSsOsRequest && equalTo((UpdateSsOsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateSsOsRequest other) {
        return provider.equals(other.provider)
                && domain.equals(other.domain)
                && config.equals(other.config)
                && active.equals(other.active)
                && extendedData.equals(other.extendedData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provider, this.domain, this.config, this.active, this.extendedData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<UpdateSsOsRequestProvider> provider = Optional.empty();

        private Optional<String> domain = Optional.empty();

        private Optional<Map<String, Object>> config = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateSsOsRequest other) {
            provider(other.getProvider());
            domain(other.getDomain());
            config(other.getConfig());
            active(other.getActive());
            extendedData(other.getExtendedData());
            return this;
        }

        /**
         * <p>SSO provider type</p>
         */
        @JsonSetter(value = "provider", nulls = Nulls.SKIP)
        public Builder provider(Optional<UpdateSsOsRequestProvider> provider) {
            this.provider = provider;
            return this;
        }

        public Builder provider(UpdateSsOsRequestProvider provider) {
            this.provider = Optional.ofNullable(provider);
            return this;
        }

        /**
         * <p>Email domain to match</p>
         */
        @JsonSetter(value = "domain", nulls = Nulls.SKIP)
        public Builder domain(Optional<String> domain) {
            this.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            this.domain = Optional.ofNullable(domain);
            return this;
        }

        /**
         * <p>Provider configuration</p>
         */
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public Builder config(Optional<Map<String, Object>> config) {
            this.config = config;
            return this;
        }

        public Builder config(Map<String, Object> config) {
            this.config = Optional.ofNullable(config);
            return this;
        }

        /**
         * <p>Enable/disable provider</p>
         */
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public Builder active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        public Builder active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Custom extended data</p>
         */
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public Builder extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        public Builder extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        public UpdateSsOsRequest build() {
            return new UpdateSsOsRequest(provider, domain, config, active, extendedData, additionalProperties);
        }
    }
}
