/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.ssos;

import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.resources.ssos.requests.CreateSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.DeleteSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.ListSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.RetrieveSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.UpdateSsOsRequest;
import com.foru.ms.api.resources.ssos.types.UpdateSsOsResponse;
import com.foru.ms.api.types.SsoListResponse;
import com.foru.ms.api.types.SsoResponse;
import com.foru.ms.api.types.SuccessResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncSsOsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSsOsClient rawClient;

    public AsyncSsOsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSsOsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSsOsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoListResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoListResponse> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoListResponse> list(ListSsOsRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoListResponse> list(ListSsOsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create an new sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> create(CreateSsOsRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create an new sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> create(CreateSsOsRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> retrieve(String id, RetrieveSsOsRequest request) {
        return this.rawClient.retrieve(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SsoResponse> retrieve(
            String id, RetrieveSsOsRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SuccessResponse> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SuccessResponse> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SuccessResponse> delete(String id, DeleteSsOsRequest request) {
        return this.rawClient.delete(id, request).thenApply(response -> response.body());
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<SuccessResponse> delete(
            String id, DeleteSsOsRequest request, RequestOptions requestOptions) {
        return this.rawClient.delete(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<UpdateSsOsResponse> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<UpdateSsOsResponse> update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<UpdateSsOsResponse> update(String id, UpdateSsOsRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public CompletableFuture<UpdateSsOsResponse> update(
            String id, UpdateSsOsRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }
}
