/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.ssos;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.ForumClientApiException;
import com.foru.ms.api.core.ForumClientException;
import com.foru.ms.api.core.ForumClientHttpResponse;
import com.foru.ms.api.core.MediaTypes;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.core.QueryStringMapper;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.errors.BadRequestError;
import com.foru.ms.api.errors.InternalServerError;
import com.foru.ms.api.errors.NotFoundError;
import com.foru.ms.api.errors.PaymentRequiredError;
import com.foru.ms.api.errors.TooManyRequestsError;
import com.foru.ms.api.errors.UnauthorizedError;
import com.foru.ms.api.resources.ssos.requests.CreateSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.DeleteSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.ListSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.RetrieveSsOsRequest;
import com.foru.ms.api.resources.ssos.requests.UpdateSsOsRequest;
import com.foru.ms.api.resources.ssos.types.UpdateSsOsResponse;
import com.foru.ms.api.types.ErrorResponse;
import com.foru.ms.api.types.SsoListResponse;
import com.foru.ms.api.types.SsoResponse;
import com.foru.ms.api.types.SuccessResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawSsOsClient {
    protected final ClientOptions clientOptions;

    public RawSsOsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoListResponse> list() {
        return list(ListSsOsRequest.builder().build());
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoListResponse> list(RequestOptions requestOptions) {
        return list(ListSsOsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoListResponse> list(ListSsOsRequest request) {
        return list(request, null);
    }

    /**
     * Retrieve a paginated list of ssos. Use cursor for pagination.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoListResponse> list(ListSsOsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("sso");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "cursor", request.getCursor().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SsoListResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Create an new sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> create(CreateSsOsRequest request) {
        return create(request, null);
    }

    /**
     * Create an new sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> create(CreateSsOsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("sso")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SsoResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> retrieve(String id) {
        return retrieve(id, RetrieveSsOsRequest.builder().build());
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> retrieve(String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveSsOsRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> retrieve(String id, RetrieveSsOsRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Retrieve an sso by ID or slug (if supported).
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SsoResponse> retrieve(
            String id, RetrieveSsOsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("sso")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SsoResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id) {
        return delete(id, DeleteSsOsRequest.builder().build());
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id, RequestOptions requestOptions) {
        return delete(id, DeleteSsOsRequest.builder().build(), requestOptions);
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(String id, DeleteSsOsRequest request) {
        return delete(id, request, null);
    }

    /**
     * Permanently delete an sso.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<SuccessResponse> delete(
            String id, DeleteSsOsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("sso")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<UpdateSsOsResponse> update(String id) {
        return update(id, UpdateSsOsRequest.builder().build());
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<UpdateSsOsResponse> update(String id, RequestOptions requestOptions) {
        return update(id, UpdateSsOsRequest.builder().build(), requestOptions);
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<UpdateSsOsResponse> update(String id, UpdateSsOsRequest request) {
        return update(id, request, null);
    }

    /**
     * Update an existing sso. Only provided fields will be modified.
     * <p><strong>Requires feature: sso</strong></p>
     */
    public ForumClientHttpResponse<UpdateSsOsResponse> update(
            String id, UpdateSsOsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("sso")
                .addPathSegment(id)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ForumClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateSsOsResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 402:
                        throw new PaymentRequiredError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ForumClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ForumClientException("Network error executing HTTP request", e);
        }
    }
}
