/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.ssos;

import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.resources.ssos.requests.DeleteSsoIdRequest;
import com.foru.ms.api.resources.ssos.requests.GetSsoIdRequest;
import com.foru.ms.api.resources.ssos.requests.GetSsoRequest;
import com.foru.ms.api.resources.ssos.requests.PatchSsoIdRequest;
import com.foru.ms.api.resources.ssos.requests.PostSsoRequest;
import com.foru.ms.api.resources.ssos.types.DeleteSsoIdResponse;
import com.foru.ms.api.resources.ssos.types.GetSsoIdResponse;
import com.foru.ms.api.resources.ssos.types.GetSsoResponse;
import com.foru.ms.api.resources.ssos.types.PatchSsoIdResponse;
import com.foru.ms.api.resources.ssos.types.PostSsoResponse;

public class SsOsClient {
    protected final ClientOptions clientOptions;

    private final RawSsOsClient rawClient;

    public SsOsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSsOsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSsOsClient withRawResponse() {
        return this.rawClient;
    }

    public GetSsoResponse listAllSsOs() {
        return this.rawClient.listAllSsOs().body();
    }

    public GetSsoResponse listAllSsOs(RequestOptions requestOptions) {
        return this.rawClient.listAllSsOs(requestOptions).body();
    }

    public GetSsoResponse listAllSsOs(GetSsoRequest request) {
        return this.rawClient.listAllSsOs(request).body();
    }

    public GetSsoResponse listAllSsOs(GetSsoRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAllSsOs(request, requestOptions).body();
    }

    public PostSsoResponse createAnSso(PostSsoRequest request) {
        return this.rawClient.createAnSso(request).body();
    }

    public PostSsoResponse createAnSso(PostSsoRequest request, RequestOptions requestOptions) {
        return this.rawClient.createAnSso(request, requestOptions).body();
    }

    public GetSsoIdResponse getAnSso(String id) {
        return this.rawClient.getAnSso(id).body();
    }

    public GetSsoIdResponse getAnSso(String id, RequestOptions requestOptions) {
        return this.rawClient.getAnSso(id, requestOptions).body();
    }

    public GetSsoIdResponse getAnSso(String id, GetSsoIdRequest request) {
        return this.rawClient.getAnSso(id, request).body();
    }

    public GetSsoIdResponse getAnSso(String id, GetSsoIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.getAnSso(id, request, requestOptions).body();
    }

    public DeleteSsoIdResponse deleteAnSso(String id) {
        return this.rawClient.deleteAnSso(id).body();
    }

    public DeleteSsoIdResponse deleteAnSso(String id, RequestOptions requestOptions) {
        return this.rawClient.deleteAnSso(id, requestOptions).body();
    }

    public DeleteSsoIdResponse deleteAnSso(String id, DeleteSsoIdRequest request) {
        return this.rawClient.deleteAnSso(id, request).body();
    }

    public DeleteSsoIdResponse deleteAnSso(String id, DeleteSsoIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteAnSso(id, request, requestOptions).body();
    }

    public PatchSsoIdResponse updateAnSso(String id) {
        return this.rawClient.updateAnSso(id).body();
    }

    public PatchSsoIdResponse updateAnSso(String id, RequestOptions requestOptions) {
        return this.rawClient.updateAnSso(id, requestOptions).body();
    }

    public PatchSsoIdResponse updateAnSso(String id, PatchSsoIdRequest request) {
        return this.rawClient.updateAnSso(id, request).body();
    }

    public PatchSsoIdResponse updateAnSso(String id, PatchSsoIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateAnSso(id, request, requestOptions).body();
    }
}
