/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.users.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListUsersRequestSort {
    public static final ListUsersRequestSort OLDEST = new ListUsersRequestSort(Value.OLDEST, "oldest");

    public static final ListUsersRequestSort NEWEST = new ListUsersRequestSort(Value.NEWEST, "newest");

    private final Value value;

    private final String string;

    ListUsersRequestSort(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListUsersRequestSort && this.string.equals(((ListUsersRequestSort) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OLDEST:
                return visitor.visitOldest();
            case NEWEST:
                return visitor.visitNewest();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListUsersRequestSort valueOf(String value) {
        switch (value) {
            case "oldest":
                return OLDEST;
            case "newest":
                return NEWEST;
            default:
                return new ListUsersRequestSort(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NEWEST,

        OLDEST,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNewest();

        T visitOldest();

        T visitUnknown(String unknownType);
    }
}
