/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.Nullable;
import com.foru.ms.api.core.NullableNonemptyFilter;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ErrorResponseError.Builder.class)
public final class ErrorResponseError {
    private final String code;

    private final String message;

    private final Optional<Object> details;

    private final Map<String, Object> additionalProperties;

    private ErrorResponseError(
            String code, String message, Optional<Object> details, Map<String, Object> additionalProperties) {
        this.code = code;
        this.message = message;
        this.details = details;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonIgnore
    public Optional<Object> getDetails() {
        if (details == null) {
            return Optional.empty();
        }
        return details;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("details")
    private Optional<Object> _getDetails() {
        return details;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ErrorResponseError && equalTo((ErrorResponseError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ErrorResponseError other) {
        return code.equals(other.code) && message.equals(other.message) && details.equals(other.details);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.code, this.message, this.details);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CodeStage builder() {
        return new Builder();
    }

    public interface CodeStage {
        MessageStage code(@NotNull String code);

        Builder from(ErrorResponseError other);
    }

    public interface MessageStage {
        _FinalStage message(@NotNull String message);
    }

    public interface _FinalStage {
        ErrorResponseError build();

        _FinalStage details(Optional<Object> details);

        _FinalStage details(Object details);

        _FinalStage details(Nullable<Object> details);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CodeStage, MessageStage, _FinalStage {
        private String code;

        private String message;

        private Optional<Object> details = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ErrorResponseError other) {
            code(other.getCode());
            message(other.getMessage());
            details(other.getDetails());
            return this;
        }

        @java.lang.Override
        @JsonSetter("code")
        public MessageStage code(@NotNull String code) {
            this.code = Objects.requireNonNull(code, "code must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("message")
        public _FinalStage message(@NotNull String message) {
            this.message = Objects.requireNonNull(message, "message must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage details(Nullable<Object> details) {
            if (details.isNull()) {
                this.details = null;
            } else if (details.isEmpty()) {
                this.details = Optional.empty();
            } else {
                this.details = Optional.of(details.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage details(Object details) {
            this.details = Optional.ofNullable(details);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "details", nulls = Nulls.SKIP)
        public _FinalStage details(Optional<Object> details) {
            this.details = details;
            return this;
        }

        @java.lang.Override
        public ErrorResponseError build() {
            return new ErrorResponseError(code, message, details, additionalProperties);
        }
    }
}
