/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InstanceListInstancesItem.Builder.class)
public final class InstanceListInstancesItem {
    private final String id;

    private final String name;

    private final String handle;

    private final OffsetDateTime createdAt;

    private final Map<String, Object> additionalProperties;

    private InstanceListInstancesItem(
            String id, String name, String handle, OffsetDateTime createdAt, Map<String, Object> additionalProperties) {
        this.id = id;
        this.name = name;
        this.handle = handle;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("handle")
    public String getHandle() {
        return handle;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InstanceListInstancesItem && equalTo((InstanceListInstancesItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InstanceListInstancesItem other) {
        return id.equals(other.id)
                && name.equals(other.name)
                && handle.equals(other.handle)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.handle, this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        NameStage id(@NotNull String id);

        Builder from(InstanceListInstancesItem other);
    }

    public interface NameStage {
        HandleStage name(@NotNull String name);
    }

    public interface HandleStage {
        CreatedAtStage handle(@NotNull String handle);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface _FinalStage {
        InstanceListInstancesItem build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, NameStage, HandleStage, CreatedAtStage, _FinalStage {
        private String id;

        private String name;

        private String handle;

        private OffsetDateTime createdAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InstanceListInstancesItem other) {
            id(other.getId());
            name(other.getName());
            handle(other.getHandle());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public HandleStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("handle")
        public CreatedAtStage handle(@NotNull String handle) {
            this.handle = Objects.requireNonNull(handle, "handle must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public InstanceListInstancesItem build() {
            return new InstanceListInstancesItem(id, name, handle, createdAt, additionalProperties);
        }
    }
}
