/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IntegrationCreate.Builder.class)
public final class IntegrationCreate {
    private final String type;

    private final String name;

    private final Map<String, Object> config;

    private final Optional<Boolean> active;

    private final Optional<Map<String, Object>> extendedData;

    private final Map<String, Object> additionalProperties;

    private IntegrationCreate(
            String type,
            String name,
            Map<String, Object> config,
            Optional<Boolean> active,
            Optional<Map<String, Object>> extendedData,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.name = name;
        this.config = config;
        this.active = active;
        this.extendedData = extendedData;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Integration type (e.g. SLACK, DISCORD)
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return Integration name
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return JSON configuration
     */
    @JsonProperty("config")
    public Map<String, Object> getConfig() {
        return config;
    }

    /**
     * @return Whether integration is active
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Custom extended data
     */
    @JsonProperty("extendedData")
    public Optional<Map<String, Object>> getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IntegrationCreate && equalTo((IntegrationCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IntegrationCreate other) {
        return type.equals(other.type)
                && name.equals(other.name)
                && config.equals(other.config)
                && active.equals(other.active)
                && extendedData.equals(other.extendedData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.name, this.config, this.active, this.extendedData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Integration type (e.g. SLACK, DISCORD)</p>
         */
        NameStage type(@NotNull String type);

        Builder from(IntegrationCreate other);
    }

    public interface NameStage {
        /**
         * <p>Integration name</p>
         */
        _FinalStage name(@NotNull String name);
    }

    public interface _FinalStage {
        IntegrationCreate build();

        /**
         * <p>JSON configuration</p>
         */
        _FinalStage config(Map<String, Object> config);

        _FinalStage putAllConfig(Map<String, Object> config);

        _FinalStage config(String key, Object value);

        /**
         * <p>Whether integration is active</p>
         */
        _FinalStage active(Optional<Boolean> active);

        _FinalStage active(Boolean active);

        /**
         * <p>Custom extended data</p>
         */
        _FinalStage extendedData(Optional<Map<String, Object>> extendedData);

        _FinalStage extendedData(Map<String, Object> extendedData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, NameStage, _FinalStage {
        private String type;

        private String name;

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        private Map<String, Object> config = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IntegrationCreate other) {
            type(other.getType());
            name(other.getName());
            config(other.getConfig());
            active(other.getActive());
            extendedData(other.getExtendedData());
            return this;
        }

        /**
         * <p>Integration type (e.g. SLACK, DISCORD)</p>
         * <p>Integration type (e.g. SLACK, DISCORD)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public NameStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Integration name</p>
         * <p>Integration name</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Custom extended data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        /**
         * <p>Custom extended data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public _FinalStage extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        /**
         * <p>Whether integration is active</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Whether integration is active</p>
         */
        @java.lang.Override
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public _FinalStage active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        /**
         * <p>JSON configuration</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage config(String key, Object value) {
            this.config.put(key, value);
            return this;
        }

        /**
         * <p>JSON configuration</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllConfig(Map<String, Object> config) {
            if (config != null) {
                this.config.putAll(config);
            }
            return this;
        }

        /**
         * <p>JSON configuration</p>
         */
        @java.lang.Override
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public _FinalStage config(Map<String, Object> config) {
            this.config.clear();
            if (config != null) {
                this.config.putAll(config);
            }
            return this;
        }

        @java.lang.Override
        public IntegrationCreate build() {
            return new IntegrationCreate(type, name, config, active, extendedData, additionalProperties);
        }
    }
}
