/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class NotificationUpdateStatus {
    public static final NotificationUpdateStatus READ = new NotificationUpdateStatus(Value.READ, "read");

    public static final NotificationUpdateStatus ARCHIVED = new NotificationUpdateStatus(Value.ARCHIVED, "archived");

    public static final NotificationUpdateStatus UNREAD = new NotificationUpdateStatus(Value.UNREAD, "unread");

    public static final NotificationUpdateStatus DISMISSED = new NotificationUpdateStatus(Value.DISMISSED, "dismissed");

    private final Value value;

    private final String string;

    NotificationUpdateStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof NotificationUpdateStatus
                        && this.string.equals(((NotificationUpdateStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case READ:
                return visitor.visitRead();
            case ARCHIVED:
                return visitor.visitArchived();
            case UNREAD:
                return visitor.visitUnread();
            case DISMISSED:
                return visitor.visitDismissed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static NotificationUpdateStatus valueOf(String value) {
        switch (value) {
            case "read":
                return READ;
            case "archived":
                return ARCHIVED;
            case "unread":
                return UNREAD;
            case "dismissed":
                return DISMISSED;
            default:
                return new NotificationUpdateStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        READ,

        UNREAD,

        DISMISSED,

        ARCHIVED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRead();

        T visitUnread();

        T visitDismissed();

        T visitArchived();

        T visitUnknown(String unknownType);
    }
}
