/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostReactionCreate.Builder.class)
public final class PostReactionCreate {
    private final PostReactionCreateType type;

    private final Optional<String> userId;

    private final Optional<Map<String, Object>> extendedData;

    private final Map<String, Object> additionalProperties;

    private PostReactionCreate(
            PostReactionCreateType type,
            Optional<String> userId,
            Optional<Map<String, Object>> extendedData,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.userId = userId;
        this.extendedData = extendedData;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Type of reaction
     */
    @JsonProperty("type")
    public PostReactionCreateType getType() {
        return type;
    }

    /**
     * @return User ID (required for API key auth, ignored for JWT auth)
     */
    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    /**
     * @return Additional custom data
     */
    @JsonProperty("extendedData")
    public Optional<Map<String, Object>> getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostReactionCreate && equalTo((PostReactionCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostReactionCreate other) {
        return type.equals(other.type) && userId.equals(other.userId) && extendedData.equals(other.extendedData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.userId, this.extendedData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Type of reaction</p>
         */
        _FinalStage type(@NotNull PostReactionCreateType type);

        Builder from(PostReactionCreate other);
    }

    public interface _FinalStage {
        PostReactionCreate build();

        /**
         * <p>User ID (required for API key auth, ignored for JWT auth)</p>
         */
        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        /**
         * <p>Additional custom data</p>
         */
        _FinalStage extendedData(Optional<Map<String, Object>> extendedData);

        _FinalStage extendedData(Map<String, Object> extendedData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private PostReactionCreateType type;

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostReactionCreate other) {
            type(other.getType());
            userId(other.getUserId());
            extendedData(other.getExtendedData());
            return this;
        }

        /**
         * <p>Type of reaction</p>
         * <p>Type of reaction</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull PostReactionCreateType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Additional custom data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        /**
         * <p>Additional custom data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public _FinalStage extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        /**
         * <p>User ID (required for API key auth, ignored for JWT auth)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        /**
         * <p>User ID (required for API key auth, ignored for JWT auth)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        @java.lang.Override
        public PostReactionCreate build() {
            return new PostReactionCreate(type, userId, extendedData, additionalProperties);
        }
    }
}
