/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostReactionListResponseDataItemsItem.Builder.class)
public final class PostReactionListResponseDataItemsItem {
    private final String id;

    private final String type;

    private final String userId;

    private final Optional<PostReactionListResponseDataItemsItemUser> user;

    private final String createdAt;

    private final Map<String, Object> additionalProperties;

    private PostReactionListResponseDataItemsItem(
            String id,
            String type,
            String userId,
            Optional<PostReactionListResponseDataItemsItemUser> user,
            String createdAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.type = type;
        this.userId = userId;
        this.user = user;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("type")
    public String getType() {
        return type;
    }

    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    @JsonProperty("user")
    public Optional<PostReactionListResponseDataItemsItemUser> getUser() {
        return user;
    }

    @JsonProperty("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostReactionListResponseDataItemsItem
                && equalTo((PostReactionListResponseDataItemsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostReactionListResponseDataItemsItem other) {
        return id.equals(other.id)
                && type.equals(other.type)
                && userId.equals(other.userId)
                && user.equals(other.user)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.type, this.userId, this.user, this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        TypeStage id(@NotNull String id);

        Builder from(PostReactionListResponseDataItemsItem other);
    }

    public interface TypeStage {
        UserIdStage type(@NotNull String type);
    }

    public interface UserIdStage {
        CreatedAtStage userId(@NotNull String userId);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull String createdAt);
    }

    public interface _FinalStage {
        PostReactionListResponseDataItemsItem build();

        _FinalStage user(Optional<PostReactionListResponseDataItemsItemUser> user);

        _FinalStage user(PostReactionListResponseDataItemsItemUser user);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdStage, TypeStage, UserIdStage, CreatedAtStage, _FinalStage {
        private String id;

        private String type;

        private String userId;

        private String createdAt;

        private Optional<PostReactionListResponseDataItemsItemUser> user = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostReactionListResponseDataItemsItem other) {
            id(other.getId());
            type(other.getType());
            userId(other.getUserId());
            user(other.getUser());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public TypeStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public UserIdStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("userId")
        public CreatedAtStage userId(@NotNull String userId) {
            this.userId = Objects.requireNonNull(userId, "userId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage user(PostReactionListResponseDataItemsItemUser user) {
            this.user = Optional.ofNullable(user);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user", nulls = Nulls.SKIP)
        public _FinalStage user(Optional<PostReactionListResponseDataItemsItemUser> user) {
            this.user = user;
            return this;
        }

        @java.lang.Override
        public PostReactionListResponseDataItemsItem build() {
            return new PostReactionListResponseDataItemsItem(id, type, userId, user, createdAt, additionalProperties);
        }
    }
}
