/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PostListType {
    public static final PostListType UPVOTED = new PostListType(Value.UPVOTED, "upvoted");

    public static final PostListType DISLIKED = new PostListType(Value.DISLIKED, "disliked");

    public static final PostListType DOWNVOTED = new PostListType(Value.DOWNVOTED, "downvoted");

    public static final PostListType CREATED = new PostListType(Value.CREATED, "created");

    public static final PostListType LIKED = new PostListType(Value.LIKED, "liked");

    private final Value value;

    private final String string;

    PostListType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof PostListType && this.string.equals(((PostListType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UPVOTED:
                return visitor.visitUpvoted();
            case DISLIKED:
                return visitor.visitDisliked();
            case DOWNVOTED:
                return visitor.visitDownvoted();
            case CREATED:
                return visitor.visitCreated();
            case LIKED:
                return visitor.visitLiked();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PostListType valueOf(String value) {
        switch (value) {
            case "upvoted":
                return UPVOTED;
            case "disliked":
                return DISLIKED;
            case "downvoted":
                return DOWNVOTED;
            case "created":
                return CREATED;
            case "liked":
                return LIKED;
            default:
                return new PostListType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CREATED,

        LIKED,

        DISLIKED,

        UPVOTED,

        DOWNVOTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCreated();

        T visitLiked();

        T visitDisliked();

        T visitUpvoted();

        T visitDownvoted();

        T visitUnknown(String unknownType);
    }
}
