/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReportCreate.Builder.class)
public final class ReportCreate {
    private final String type;

    private final Optional<String> description;

    private final Optional<String> userId;

    private final Optional<String> reportedId;

    private final Optional<String> threadId;

    private final Optional<String> postId;

    private final Optional<String> privateMessageId;

    private final Map<String, Object> additionalProperties;

    private ReportCreate(
            String type,
            Optional<String> description,
            Optional<String> userId,
            Optional<String> reportedId,
            Optional<String> threadId,
            Optional<String> postId,
            Optional<String> privateMessageId,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.description = description;
        this.userId = userId;
        this.reportedId = reportedId;
        this.threadId = threadId;
        this.postId = postId;
        this.privateMessageId = privateMessageId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Report type (e.g. spam, abuse)
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return Reason for reporting
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Reporter user ID (required for API key auth, ignored for JWT auth)
     */
    @JsonProperty("userId")
    public Optional<String> getUserId() {
        return userId;
    }

    /**
     * @return ID of user being reported
     */
    @JsonProperty("reportedId")
    public Optional<String> getReportedId() {
        return reportedId;
    }

    /**
     * @return ID of thread being reported
     */
    @JsonProperty("threadId")
    public Optional<String> getThreadId() {
        return threadId;
    }

    /**
     * @return ID of post being reported
     */
    @JsonProperty("postId")
    public Optional<String> getPostId() {
        return postId;
    }

    /**
     * @return ID of private message being reported
     */
    @JsonProperty("privateMessageId")
    public Optional<String> getPrivateMessageId() {
        return privateMessageId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReportCreate && equalTo((ReportCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReportCreate other) {
        return type.equals(other.type)
                && description.equals(other.description)
                && userId.equals(other.userId)
                && reportedId.equals(other.reportedId)
                && threadId.equals(other.threadId)
                && postId.equals(other.postId)
                && privateMessageId.equals(other.privateMessageId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.type,
                this.description,
                this.userId,
                this.reportedId,
                this.threadId,
                this.postId,
                this.privateMessageId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Report type (e.g. spam, abuse)</p>
         */
        _FinalStage type(@NotNull String type);

        Builder from(ReportCreate other);
    }

    public interface _FinalStage {
        ReportCreate build();

        /**
         * <p>Reason for reporting</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Reporter user ID (required for API key auth, ignored for JWT auth)</p>
         */
        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        /**
         * <p>ID of user being reported</p>
         */
        _FinalStage reportedId(Optional<String> reportedId);

        _FinalStage reportedId(String reportedId);

        /**
         * <p>ID of thread being reported</p>
         */
        _FinalStage threadId(Optional<String> threadId);

        _FinalStage threadId(String threadId);

        /**
         * <p>ID of post being reported</p>
         */
        _FinalStage postId(Optional<String> postId);

        _FinalStage postId(String postId);

        /**
         * <p>ID of private message being reported</p>
         */
        _FinalStage privateMessageId(Optional<String> privateMessageId);

        _FinalStage privateMessageId(String privateMessageId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private String type;

        private Optional<String> privateMessageId = Optional.empty();

        private Optional<String> postId = Optional.empty();

        private Optional<String> threadId = Optional.empty();

        private Optional<String> reportedId = Optional.empty();

        private Optional<String> userId = Optional.empty();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ReportCreate other) {
            type(other.getType());
            description(other.getDescription());
            userId(other.getUserId());
            reportedId(other.getReportedId());
            threadId(other.getThreadId());
            postId(other.getPostId());
            privateMessageId(other.getPrivateMessageId());
            return this;
        }

        /**
         * <p>Report type (e.g. spam, abuse)</p>
         * <p>Report type (e.g. spam, abuse)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>ID of private message being reported</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage privateMessageId(String privateMessageId) {
            this.privateMessageId = Optional.ofNullable(privateMessageId);
            return this;
        }

        /**
         * <p>ID of private message being reported</p>
         */
        @java.lang.Override
        @JsonSetter(value = "privateMessageId", nulls = Nulls.SKIP)
        public _FinalStage privateMessageId(Optional<String> privateMessageId) {
            this.privateMessageId = privateMessageId;
            return this;
        }

        /**
         * <p>ID of post being reported</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage postId(String postId) {
            this.postId = Optional.ofNullable(postId);
            return this;
        }

        /**
         * <p>ID of post being reported</p>
         */
        @java.lang.Override
        @JsonSetter(value = "postId", nulls = Nulls.SKIP)
        public _FinalStage postId(Optional<String> postId) {
            this.postId = postId;
            return this;
        }

        /**
         * <p>ID of thread being reported</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage threadId(String threadId) {
            this.threadId = Optional.ofNullable(threadId);
            return this;
        }

        /**
         * <p>ID of thread being reported</p>
         */
        @java.lang.Override
        @JsonSetter(value = "threadId", nulls = Nulls.SKIP)
        public _FinalStage threadId(Optional<String> threadId) {
            this.threadId = threadId;
            return this;
        }

        /**
         * <p>ID of user being reported</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage reportedId(String reportedId) {
            this.reportedId = Optional.ofNullable(reportedId);
            return this;
        }

        /**
         * <p>ID of user being reported</p>
         */
        @java.lang.Override
        @JsonSetter(value = "reportedId", nulls = Nulls.SKIP)
        public _FinalStage reportedId(Optional<String> reportedId) {
            this.reportedId = reportedId;
            return this;
        }

        /**
         * <p>Reporter user ID (required for API key auth, ignored for JWT auth)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        /**
         * <p>Reporter user ID (required for API key auth, ignored for JWT auth)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "userId", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        /**
         * <p>Reason for reporting</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Reason for reporting</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public ReportCreate build() {
            return new ReportCreate(
                    type, description, userId, reportedId, threadId, postId, privateMessageId, additionalProperties);
        }
    }
}
