/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SsoCreate.Builder.class)
public final class SsoCreate {
    private final SsoCreateProvider provider;

    private final String domain;

    private final Map<String, Object> config;

    private final Optional<Boolean> active;

    private final Optional<Map<String, Object>> extendedData;

    private final Map<String, Object> additionalProperties;

    private SsoCreate(
            SsoCreateProvider provider,
            String domain,
            Map<String, Object> config,
            Optional<Boolean> active,
            Optional<Map<String, Object>> extendedData,
            Map<String, Object> additionalProperties) {
        this.provider = provider;
        this.domain = domain;
        this.config = config;
        this.active = active;
        this.extendedData = extendedData;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return SSO provider type
     */
    @JsonProperty("provider")
    public SsoCreateProvider getProvider() {
        return provider;
    }

    /**
     * @return Email domain to match (e.g. 'acme.com')
     */
    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    /**
     * @return Provider configuration (clientId, issuer, etc.)
     */
    @JsonProperty("config")
    public Map<String, Object> getConfig() {
        return config;
    }

    /**
     * @return Whether SSO is active
     */
    @JsonProperty("active")
    public Optional<Boolean> getActive() {
        return active;
    }

    /**
     * @return Custom extended data
     */
    @JsonProperty("extendedData")
    public Optional<Map<String, Object>> getExtendedData() {
        return extendedData;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SsoCreate && equalTo((SsoCreate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SsoCreate other) {
        return provider.equals(other.provider)
                && domain.equals(other.domain)
                && config.equals(other.config)
                && active.equals(other.active)
                && extendedData.equals(other.extendedData);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.provider, this.domain, this.config, this.active, this.extendedData);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProviderStage builder() {
        return new Builder();
    }

    public interface ProviderStage {
        /**
         * <p>SSO provider type</p>
         */
        DomainStage provider(@NotNull SsoCreateProvider provider);

        Builder from(SsoCreate other);
    }

    public interface DomainStage {
        /**
         * <p>Email domain to match (e.g. 'acme.com')</p>
         */
        _FinalStage domain(@NotNull String domain);
    }

    public interface _FinalStage {
        SsoCreate build();

        /**
         * <p>Provider configuration (clientId, issuer, etc.)</p>
         */
        _FinalStage config(Map<String, Object> config);

        _FinalStage putAllConfig(Map<String, Object> config);

        _FinalStage config(String key, Object value);

        /**
         * <p>Whether SSO is active</p>
         */
        _FinalStage active(Optional<Boolean> active);

        _FinalStage active(Boolean active);

        /**
         * <p>Custom extended data</p>
         */
        _FinalStage extendedData(Optional<Map<String, Object>> extendedData);

        _FinalStage extendedData(Map<String, Object> extendedData);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProviderStage, DomainStage, _FinalStage {
        private SsoCreateProvider provider;

        private String domain;

        private Optional<Map<String, Object>> extendedData = Optional.empty();

        private Optional<Boolean> active = Optional.empty();

        private Map<String, Object> config = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SsoCreate other) {
            provider(other.getProvider());
            domain(other.getDomain());
            config(other.getConfig());
            active(other.getActive());
            extendedData(other.getExtendedData());
            return this;
        }

        /**
         * <p>SSO provider type</p>
         * <p>SSO provider type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("provider")
        public DomainStage provider(@NotNull SsoCreateProvider provider) {
            this.provider = Objects.requireNonNull(provider, "provider must not be null");
            return this;
        }

        /**
         * <p>Email domain to match (e.g. 'acme.com')</p>
         * <p>Email domain to match (e.g. 'acme.com')</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public _FinalStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        /**
         * <p>Custom extended data</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extendedData(Map<String, Object> extendedData) {
            this.extendedData = Optional.ofNullable(extendedData);
            return this;
        }

        /**
         * <p>Custom extended data</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extendedData", nulls = Nulls.SKIP)
        public _FinalStage extendedData(Optional<Map<String, Object>> extendedData) {
            this.extendedData = extendedData;
            return this;
        }

        /**
         * <p>Whether SSO is active</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage active(Boolean active) {
            this.active = Optional.ofNullable(active);
            return this;
        }

        /**
         * <p>Whether SSO is active</p>
         */
        @java.lang.Override
        @JsonSetter(value = "active", nulls = Nulls.SKIP)
        public _FinalStage active(Optional<Boolean> active) {
            this.active = active;
            return this;
        }

        /**
         * <p>Provider configuration (clientId, issuer, etc.)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage config(String key, Object value) {
            this.config.put(key, value);
            return this;
        }

        /**
         * <p>Provider configuration (clientId, issuer, etc.)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllConfig(Map<String, Object> config) {
            if (config != null) {
                this.config.putAll(config);
            }
            return this;
        }

        /**
         * <p>Provider configuration (clientId, issuer, etc.)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "config", nulls = Nulls.SKIP)
        public _FinalStage config(Map<String, Object> config) {
            this.config.clear();
            if (config != null) {
                this.config.putAll(config);
            }
            return this;
        }

        @java.lang.Override
        public SsoCreate build() {
            return new SsoCreate(provider, domain, config, active, extendedData, additionalProperties);
        }
    }
}
