/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TagList.Builder.class)
public final class TagList {
    private final Optional<Double> limit;

    private final Optional<String> cursor;

    private final Optional<String> search;

    private final Map<String, Object> additionalProperties;

    private TagList(
            Optional<Double> limit,
            Optional<String> cursor,
            Optional<String> search,
            Map<String, Object> additionalProperties) {
        this.limit = limit;
        this.cursor = cursor;
        this.search = search;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Items per page (max 75)
     */
    @JsonProperty("limit")
    public Optional<Double> getLimit() {
        return limit;
    }

    /**
     * @return Cursor for pagination
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    /**
     * @return Search tags by name or description
     */
    @JsonProperty("search")
    public Optional<String> getSearch() {
        return search;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TagList && equalTo((TagList) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TagList other) {
        return limit.equals(other.limit) && cursor.equals(other.cursor) && search.equals(other.search);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.limit, this.cursor, this.search);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Double> limit = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Optional<String> search = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TagList other) {
            limit(other.getLimit());
            cursor(other.getCursor());
            search(other.getSearch());
            return this;
        }

        /**
         * <p>Items per page (max 75)</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Double> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Double limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Cursor for pagination</p>
         */
        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * <p>Search tags by name or description</p>
         */
        @JsonSetter(value = "search", nulls = Nulls.SKIP)
        public Builder search(Optional<String> search) {
            this.search = search;
            return this;
        }

        public Builder search(String search) {
            this.search = Optional.ofNullable(search);
            return this;
        }

        public TagList build() {
            return new TagList(limit, cursor, search, additionalProperties);
        }
    }
}
