/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TeamMemberStatus {
    public static final TeamMemberStatus ACCEPTED = new TeamMemberStatus(Value.ACCEPTED, "ACCEPTED");

    public static final TeamMemberStatus DECLINED = new TeamMemberStatus(Value.DECLINED, "DECLINED");

    public static final TeamMemberStatus PENDING = new TeamMemberStatus(Value.PENDING, "PENDING");

    private final Value value;

    private final String string;

    TeamMemberStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TeamMemberStatus && this.string.equals(((TeamMemberStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACCEPTED:
                return visitor.visitAccepted();
            case DECLINED:
                return visitor.visitDeclined();
            case PENDING:
                return visitor.visitPending();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TeamMemberStatus valueOf(String value) {
        switch (value) {
            case "ACCEPTED":
                return ACCEPTED;
            case "DECLINED":
                return DECLINED;
            case "PENDING":
                return PENDING;
            default:
                return new TeamMemberStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PENDING,

        ACCEPTED,

        DECLINED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPending();

        T visitAccepted();

        T visitDeclined();

        T visitUnknown(String unknownType);
    }
}
