/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ThreadPostResponseDataCount.Builder.class)
public final class ThreadPostResponseDataCount {
    private final double reactions;

    private final Map<String, Object> additionalProperties;

    private ThreadPostResponseDataCount(double reactions, Map<String, Object> additionalProperties) {
        this.reactions = reactions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("reactions")
    public double getReactions() {
        return reactions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ThreadPostResponseDataCount && equalTo((ThreadPostResponseDataCount) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ThreadPostResponseDataCount other) {
        return reactions == other.reactions;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.reactions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ReactionsStage builder() {
        return new Builder();
    }

    public interface ReactionsStage {
        _FinalStage reactions(double reactions);

        Builder from(ThreadPostResponseDataCount other);
    }

    public interface _FinalStage {
        ThreadPostResponseDataCount build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ReactionsStage, _FinalStage {
        private double reactions;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ThreadPostResponseDataCount other) {
            reactions(other.getReactions());
            return this;
        }

        @java.lang.Override
        @JsonSetter("reactions")
        public _FinalStage reactions(double reactions) {
            this.reactions = reactions;
            return this;
        }

        @java.lang.Override
        public ThreadPostResponseDataCount build() {
            return new ThreadPostResponseDataCount(reactions, additionalProperties);
        }
    }
}
