/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ThreadPostListResponseData.Builder.class)
public final class ThreadPostListResponseData {
    private final List<ThreadPostListResponseDataItemsItem> items;

    private final Optional<String> nextCursor;

    private final int count;

    private final Map<String, Object> additionalProperties;

    private ThreadPostListResponseData(
            List<ThreadPostListResponseDataItemsItem> items,
            Optional<String> nextCursor,
            int count,
            Map<String, Object> additionalProperties) {
        this.items = items;
        this.nextCursor = nextCursor;
        this.count = count;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("items")
    public List<ThreadPostListResponseDataItemsItem> getItems() {
        return items;
    }

    @JsonProperty("nextCursor")
    public Optional<String> getNextCursor() {
        return nextCursor;
    }

    @JsonProperty("count")
    public int getCount() {
        return count;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ThreadPostListResponseData && equalTo((ThreadPostListResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ThreadPostListResponseData other) {
        return items.equals(other.items) && nextCursor.equals(other.nextCursor) && count == other.count;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.items, this.nextCursor, this.count);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CountStage builder() {
        return new Builder();
    }

    public interface CountStage {
        _FinalStage count(int count);

        Builder from(ThreadPostListResponseData other);
    }

    public interface _FinalStage {
        ThreadPostListResponseData build();

        _FinalStage items(List<ThreadPostListResponseDataItemsItem> items);

        _FinalStage addItems(ThreadPostListResponseDataItemsItem items);

        _FinalStage addAllItems(List<ThreadPostListResponseDataItemsItem> items);

        _FinalStage nextCursor(Optional<String> nextCursor);

        _FinalStage nextCursor(String nextCursor);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CountStage, _FinalStage {
        private int count;

        private Optional<String> nextCursor = Optional.empty();

        private List<ThreadPostListResponseDataItemsItem> items = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ThreadPostListResponseData other) {
            items(other.getItems());
            nextCursor(other.getNextCursor());
            count(other.getCount());
            return this;
        }

        @java.lang.Override
        @JsonSetter("count")
        public _FinalStage count(int count) {
            this.count = count;
            return this;
        }

        @java.lang.Override
        public _FinalStage nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "nextCursor", nulls = Nulls.SKIP)
        public _FinalStage nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllItems(List<ThreadPostListResponseDataItemsItem> items) {
            if (items != null) {
                this.items.addAll(items);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addItems(ThreadPostListResponseDataItemsItem items) {
            this.items.add(items);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "items", nulls = Nulls.SKIP)
        public _FinalStage items(List<ThreadPostListResponseDataItemsItem> items) {
            this.items.clear();
            if (items != null) {
                this.items.addAll(items);
            }
            return this;
        }

        @java.lang.Override
        public ThreadPostListResponseData build() {
            return new ThreadPostListResponseData(items, nextCursor, count, additionalProperties);
        }
    }
}
