/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.foru.ms.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserFollowingResponseData.Builder.class)
public final class UserFollowingResponseData {
    private final String id;

    private final String followerId;

    private final String followingId;

    private final Optional<UserFollowingResponseDataFollowing> following;

    private final String createdAt;

    private final Map<String, Object> additionalProperties;

    private UserFollowingResponseData(
            String id,
            String followerId,
            String followingId,
            Optional<UserFollowingResponseDataFollowing> following,
            String createdAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.followerId = followerId;
        this.followingId = followingId;
        this.following = following;
        this.createdAt = createdAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("followerId")
    public String getFollowerId() {
        return followerId;
    }

    @JsonProperty("followingId")
    public String getFollowingId() {
        return followingId;
    }

    @JsonProperty("following")
    public Optional<UserFollowingResponseDataFollowing> getFollowing() {
        return following;
    }

    @JsonProperty("createdAt")
    public String getCreatedAt() {
        return createdAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserFollowingResponseData && equalTo((UserFollowingResponseData) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserFollowingResponseData other) {
        return id.equals(other.id)
                && followerId.equals(other.followerId)
                && followingId.equals(other.followingId)
                && following.equals(other.following)
                && createdAt.equals(other.createdAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.followerId, this.followingId, this.following, this.createdAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        FollowerIdStage id(@NotNull String id);

        Builder from(UserFollowingResponseData other);
    }

    public interface FollowerIdStage {
        FollowingIdStage followerId(@NotNull String followerId);
    }

    public interface FollowingIdStage {
        CreatedAtStage followingId(@NotNull String followingId);
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull String createdAt);
    }

    public interface _FinalStage {
        UserFollowingResponseData build();

        _FinalStage following(Optional<UserFollowingResponseDataFollowing> following);

        _FinalStage following(UserFollowingResponseDataFollowing following);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, FollowerIdStage, FollowingIdStage, CreatedAtStage, _FinalStage {
        private String id;

        private String followerId;

        private String followingId;

        private String createdAt;

        private Optional<UserFollowingResponseDataFollowing> following = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UserFollowingResponseData other) {
            id(other.getId());
            followerId(other.getFollowerId());
            followingId(other.getFollowingId());
            following(other.getFollowing());
            createdAt(other.getCreatedAt());
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public FollowerIdStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("followerId")
        public FollowingIdStage followerId(@NotNull String followerId) {
            this.followerId = Objects.requireNonNull(followerId, "followerId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("followingId")
        public CreatedAtStage followingId(@NotNull String followingId) {
            this.followingId = Objects.requireNonNull(followingId, "followingId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull String createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage following(UserFollowingResponseDataFollowing following) {
            this.following = Optional.ofNullable(following);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "following", nulls = Nulls.SKIP)
        public _FinalStage following(Optional<UserFollowingResponseDataFollowing> following) {
            this.following = following;
            return this;
        }

        @java.lang.Override
        public UserFollowingResponseData build() {
            return new UserFollowingResponseData(
                    id, followerId, followingId, following, createdAt, additionalProperties);
        }
    }
}
