/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.foru.ms.api.resources.webhooks;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.foru.ms.api.core.ClientOptions;
import com.foru.ms.api.core.ForumClientApiException;
import com.foru.ms.api.core.ForumClientException;
import com.foru.ms.api.core.ForumClientHttpResponse;
import com.foru.ms.api.core.MediaTypes;
import com.foru.ms.api.core.ObjectMappers;
import com.foru.ms.api.core.QueryStringMapper;
import com.foru.ms.api.core.RequestOptions;
import com.foru.ms.api.errors.BadRequestError;
import com.foru.ms.api.errors.InternalServerError;
import com.foru.ms.api.errors.NotFoundError;
import com.foru.ms.api.errors.PaymentRequiredError;
import com.foru.ms.api.errors.TooManyRequestsError;
import com.foru.ms.api.errors.UnauthorizedError;
import com.foru.ms.api.resources.webhooks.requests.CreateWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.DeleteDeliveryWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.DeleteWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.ListDeliveriesWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.ListWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.RetrieveDeliveryWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.RetrieveWebhooksRequest;
import com.foru.ms.api.resources.webhooks.requests.UpdateWebhooksRequest;
import com.foru.ms.api.resources.webhooks.types.RetrieveDeliveryWebhooksResponse;
import com.foru.ms.api.resources.webhooks.types.UpdateWebhooksResponse;
import com.foru.ms.api.types.ErrorResponse;
import com.foru.ms.api.types.SuccessResponse;
import com.foru.ms.api.types.WebhookDeliveryListResponse;
import com.foru.ms.api.types.WebhookListResponse;
import com.foru.ms.api.types.WebhookResponse;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawWebhooksClient {
    protected final ClientOptions clientOptions;

    public AsyncRawWebhooksClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve a paginated list of webhooks. Use cursor for pagination.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookListResponse>> list() {
        return list(ListWebhooksRequest.builder().build());
    }

    /**
     * Retrieve a paginated list of webhooks. Use cursor for pagination.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookListResponse>> list(RequestOptions requestOptions) {
        return list(ListWebhooksRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve a paginated list of webhooks. Use cursor for pagination.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookListResponse>> list(ListWebhooksRequest request) {
        return list(request, null);
    }

    /**
     * Retrieve a paginated list of webhooks. Use cursor for pagination.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookListResponse>> list(
            ListWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "cursor", request.getCursor().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<WebhookListResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookListResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 402:
                                future.completeExceptionally(new PaymentRequiredError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Create a new webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> create(CreateWebhooksRequest request) {
        return create(request, null);
    }

    /**
     * Create a new webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> create(
            CreateWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<WebhookResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 402:
                                future.completeExceptionally(new PaymentRequiredError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Retrieve a webhook by ID or slug (if supported).
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> retrieve(String id) {
        return retrieve(id, RetrieveWebhooksRequest.builder().build());
    }

    /**
     * Retrieve a webhook by ID or slug (if supported).
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> retrieve(
            String id, RequestOptions requestOptions) {
        return retrieve(id, RetrieveWebhooksRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve a webhook by ID or slug (if supported).
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> retrieve(
            String id, RetrieveWebhooksRequest request) {
        return retrieve(id, request, null);
    }

    /**
     * Retrieve a webhook by ID or slug (if supported).
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookResponse>> retrieve(
            String id, RetrieveWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<WebhookResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 402:
                                future.completeExceptionally(new PaymentRequiredError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Permanently delete a webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> delete(String id) {
        return delete(id, DeleteWebhooksRequest.builder().build());
    }

    /**
     * Permanently delete a webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> delete(
            String id, RequestOptions requestOptions) {
        return delete(id, DeleteWebhooksRequest.builder().build(), requestOptions);
    }

    /**
     * Permanently delete a webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> delete(
            String id, DeleteWebhooksRequest request) {
        return delete(id, request, null);
    }

    /**
     * Permanently delete a webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> delete(
            String id, DeleteWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<SuccessResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 402:
                                future.completeExceptionally(new PaymentRequiredError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Update an existing webhook. Only provided fields will be modified.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<UpdateWebhooksResponse>> update(String id) {
        return update(id, UpdateWebhooksRequest.builder().build());
    }

    /**
     * Update an existing webhook. Only provided fields will be modified.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<UpdateWebhooksResponse>> update(
            String id, RequestOptions requestOptions) {
        return update(id, UpdateWebhooksRequest.builder().build(), requestOptions);
    }

    /**
     * Update an existing webhook. Only provided fields will be modified.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<UpdateWebhooksResponse>> update(
            String id, UpdateWebhooksRequest request) {
        return update(id, request, null);
    }

    /**
     * Update an existing webhook. Only provided fields will be modified.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<UpdateWebhooksResponse>> update(
            String id, UpdateWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ForumClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<UpdateWebhooksResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateWebhooksResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 402:
                                future.completeExceptionally(new PaymentRequiredError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Retrieve a paginated list of deliveries for Webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookDeliveryListResponse>> listDeliveries(String id) {
        return listDeliveries(id, ListDeliveriesWebhooksRequest.builder().build());
    }

    /**
     * Retrieve a paginated list of deliveries for Webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookDeliveryListResponse>> listDeliveries(
            String id, RequestOptions requestOptions) {
        return listDeliveries(id, ListDeliveriesWebhooksRequest.builder().build(), requestOptions);
    }

    /**
     * Retrieve a paginated list of deliveries for Webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookDeliveryListResponse>> listDeliveries(
            String id, ListDeliveriesWebhooksRequest request) {
        return listDeliveries(id, request, null);
    }

    /**
     * Retrieve a paginated list of deliveries for Webhook.
     * <p><strong>Requires feature: webhooks</strong></p>
     */
    public CompletableFuture<ForumClientHttpResponse<WebhookDeliveryListResponse>> listDeliveries(
            String id, ListDeliveriesWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .addPathSegments("deliveries");
        if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "cursor", request.getCursor().get(), false);
        }
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<WebhookDeliveryListResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, WebhookDeliveryListResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<ForumClientHttpResponse<RetrieveDeliveryWebhooksResponse>> retrieveDelivery(
            String id, String subId) {
        return retrieveDelivery(
                id, subId, RetrieveDeliveryWebhooksRequest.builder().build());
    }

    public CompletableFuture<ForumClientHttpResponse<RetrieveDeliveryWebhooksResponse>> retrieveDelivery(
            String id, String subId, RequestOptions requestOptions) {
        return retrieveDelivery(
                id, subId, RetrieveDeliveryWebhooksRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<ForumClientHttpResponse<RetrieveDeliveryWebhooksResponse>> retrieveDelivery(
            String id, String subId, RetrieveDeliveryWebhooksRequest request) {
        return retrieveDelivery(id, subId, request, null);
    }

    public CompletableFuture<ForumClientHttpResponse<RetrieveDeliveryWebhooksResponse>> retrieveDelivery(
            String id, String subId, RetrieveDeliveryWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .addPathSegments("deliveries")
                .addPathSegment(subId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<RetrieveDeliveryWebhooksResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, RetrieveDeliveryWebhooksResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> deleteDelivery(String id, String subId) {
        return deleteDelivery(id, subId, DeleteDeliveryWebhooksRequest.builder().build());
    }

    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> deleteDelivery(
            String id, String subId, RequestOptions requestOptions) {
        return deleteDelivery(id, subId, DeleteDeliveryWebhooksRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> deleteDelivery(
            String id, String subId, DeleteDeliveryWebhooksRequest request) {
        return deleteDelivery(id, subId, request, null);
    }

    public CompletableFuture<ForumClientHttpResponse<SuccessResponse>> deleteDelivery(
            String id, String subId, DeleteDeliveryWebhooksRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("webhooks")
                .addPathSegment(id)
                .addPathSegments("deliveries")
                .addPathSegment(subId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<ForumClientHttpResponse<SuccessResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ForumClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 429:
                                future.completeExceptionally(new TooManyRequestsError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ForumClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ForumClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
